/* DSblock model generated by Dymola from Modelica model Masterthesis.Models.mimo_processmodel
 Dymola Version 2017 FD01 (64-bit), 2016-10-11 translated this at Sat Sep 16 16:22:58 2017

   */
#ifndef DYN_MULTINSTANCE
#define DYN_MULTINSTANCE 1
#endif

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

BreakSectionFunctionDef(1)
BreakSectionFunctionDef(0)
#define NX_    20
#define NX2_   0
#define NU_    2
#define NY_    2
#define NW_    179
#define NP_    62
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -4694403
#define NHash2_ -72168814
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    24
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 8
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 12
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Masterthesis.Models.mimo_processmodel";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/juliu/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
DYMOLA_STATIC const char*GUIDString="{86d85f69-bea1-49fa-a38b-193d54ccffd7}";
DYMOLA_STATIC const double cvodeTolerance=1E-005;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[26]={5 , 4 , 1 , 6 , 11 , 16 , 4 , 2 , 7 , 12 , 17
   , 4 , 3 , 8 , 13 , 18 , 4 , 4 , 9 , 14 , 19 , 4 , 5 , 10 , 15 , 20};
DYMOLA_STATIC int QJacobianGC_[101]={
1 , 1 , 0 , 0 , 0 , 6 , 6 , 0 , 0 , 0 , 11 , 11 , 0 , 0 , 0 , 16 , 16 , 0 , 0 , 0
   , 2 , 0 , 2 , 0 , 0 , 7 , 0 , 7 , 0 , 0 , 12 , 0 , 12 , 0 , 0 , 17 , 0 , 17
   , 0 , 0 , 3 , 0 , 0 , 3 , 0 , 8 , 0 , 0 , 8 , 0 , 13 , 0 , 0 , 13 , 0 , 18 , 0
   , 0 , 18 , 0 , 4 , 0 , 0 , 0 , 4 , 9 , 0 , 0 , 0 , 9 , 14 , 0 , 0 , 0 , 14 , 19
   , 0 , 0 , 0 , 19 , 5 , 0 , 0 , 0 , 0 , 10 , 0 , 0 , 0 , 0 , 15 , 0 , 0 , 0 , 0
   , 20 , 0 , 0 , 0 , 0 , 0};
DYMOLA_STATIC double QJacobianCD_[21]={0  , 44 , 50 , 54 , 56 , 56 , 99 , 100 , 99
   , 96 , 91 , 154 , 150 , 144 , 136 , 126 , 209 , 200 , 189 , 176 , 161};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 2;
DYNX(W_,1) = 6;
DYNX(W_,2) = 2;
DYNX(W_,35) = 2;
DYNX(W_,66) = 6;
DYNX(W_,67) = 1;
DYNX(W_,68) = 5;
DYNX(W_,91) = 6;
DYNX(W_,92) = 1;
DYNX(W_,93) = 5;
DYNX(W_,102) = 2;
DYNX(W_,107) = 2;
DYNX(W_,138) = 6;
DYNX(W_,139) = 1;
DYNX(W_,140) = 5;
DYNX(W_,163) = 6;
DYNX(W_,164) = 1;
DYNX(W_,165) = 5;
DYNX(W_,174) = 2;
DYNX(W_,60) = 1;
DYNX(W_,69) = 0.0;
DYNX(W_,70) = 0.0;
DYNX(W_,71) = 0.0;
DYNX(W_,72) = 0.0;
DYNX(W_,73) = 0.0;
DYNX(W_,75) = 0.0;
DYNX(W_,85) = 1;
DYNX(W_,94) = 0.0;
DYNX(W_,95) = 0.0;
DYNX(W_,96) = 0.0;
DYNX(W_,97) = 0.0;
DYNX(W_,98) = 0.0;
DYNX(W_,100) = 0.0;
DYNX(W_,132) = 1;
DYNX(W_,141) = 0.0;
DYNX(W_,142) = 0.0;
DYNX(W_,143) = 0.0;
DYNX(W_,144) = 0.0;
DYNX(W_,145) = 0.0;
DYNX(W_,147) = 0.0;
DYNX(W_,157) = 1;
DYNX(W_,166) = 0.0;
DYNX(W_,167) = 0.0;
DYNX(W_,168) = 0.0;
DYNX(W_,169) = 0.0;
DYNX(W_,170) = 0.0;
DYNX(W_,172) = 0.0;
#endif
BoundParameterSection
DYNX(W_,3) = DYNX(DP_,0);
DYNX(W_,4) = DYNX(DP_,1);
DYNX(W_,5) = DYNX(DP_,2);
DYNX(W_,6) = DYNX(DP_,3);
DYNX(W_,7) = DYNX(DP_,4);
DYNX(W_,8) = DYNX(DP_,5);
DYNX(W_,9) = DYNX(DP_,6);
DYNX(W_,10) = DYNX(DP_,7);
DYNX(W_,11) = DYNX(DP_,8);
DYNX(W_,12) = DYNX(DP_,9);
DYNX(W_,13) = DYNX(DP_,10);
DYNX(W_,14) = DYNX(DP_,11);
DYNX(W_,15) = DYNX(DP_,12);
DYNX(W_,16) = DYNX(DP_,13);
DYNX(W_,17) = DYNX(DP_,14);
DYNX(W_,18) = DYNX(DP_,15);
DYNX(W_,19) = DYNX(DP_,16);
DYNX(W_,20) = DYNX(DP_,17);
DYNX(W_,21) = DYNX(DP_,18);
DYNX(W_,22) = DYNX(DP_,19);
DYNX(W_,23) = DYNX(DP_,20);
DYNX(W_,24) = DYNX(DP_,21);
DYNX(W_,25) = DYNX(DP_,22);
DYNX(W_,26) = DYNX(DP_,23);
DYNX(W_,27) = DYNX(DP_,24);
DYNX(W_,28) = DYNX(DP_,25);
DYNX(W_,29) = DYNX(DP_,26);
DYNX(W_,30) = DYNX(DP_,27);
DYNX(W_,31) = DYNX(DP_,28);
DYNX(W_,32) = DYNX(DP_,29);
DYNX(W_,33) = DYNX(DP_,30);
DYNX(W_,34) = DYNX(DP_,31);
DYNX(W_,36) = DYNX(W_,3);
DYNX(W_,37) = DYNX(W_,4);
DYNX(W_,38) = DYNX(W_,7);
DYNX(W_,39) = DYNX(W_,8);
DYNX(W_,40) = DYNX(W_,9);
DYNX(W_,41) = DYNX(W_,10);
DYNX(W_,42) = DYNX(W_,11);
DYNX(W_,43) = DYNX(W_,12);
DYNX(W_,44) = DYNX(W_,13);
DYNX(W_,45) = DYNX(W_,14);
DYNX(W_,46) = DYNX(W_,15);
DYNX(W_,47) = DYNX(W_,16);
DYNX(W_,48) = DYNX(W_,17);
DYNX(W_,49) = DYNX(W_,18);
DYNX(W_,50) = DYNX(W_,31);
DYNX(W_,51) = DYNX(W_,32);
DYNX(W_,53) = DYNX(W_,36);
DYNX(W_,54) = DYNX(W_,38);
DYNX(W_,55) = DYNX(W_,39);
DYNX(W_,56) = DYNX(W_,40);
DYNX(W_,57) = DYNX(W_,41);
DYNX(W_,58) = DYNX(W_,42);
DYNX(W_,59) = DYNX(W_,43);
DYNX(W_,74) = DYNX(W_,53);
DYNX(DYNhelp,0) = DYNX(W_,54)*DYNX(W_,54)+DYNX(W_,55)*DYNX(W_,55)+DYNX(W_,56)*
  DYNX(W_,56);
DYNX(DYNhelp,1) = DYNX(W_,57)*DYNX(W_,57);
DYNX(DYNhelp,2) = sqrtGuarded(DYNX(DYNhelp,0)+DYNX(DYNhelp,1)+DYNX(W_,58)*
  DYNX(W_,58)+DYNX(W_,59)*DYNX(W_,59),"system.miso[1].transferFunction[1].a[1]*system.miso[1].transferFunction[1].a[1]+system.miso[1].transferFunction[1].a[2]*system.miso[1].transferFunction[1].a[2]+system.miso[1].transferFunction[1].a[3]*system.miso[1].transferFunction[1].a[3]+system.miso[1].transferFunction[1].a[4]*system.miso[1].transferFunction[1].a[4]+system.miso[1].transferFunction[1].a[5]*system.miso[1].transferFunction[1].a[...");
DYNX(W_,76) = IF DYNX(W_,59) > 1E-013*DYNX(DYNhelp,2) THEN DYNX(W_,59) ELSE 1.0;
DYNX(W_,78) = DYNX(W_,37);
DYNX(W_,79) = DYNX(W_,44);
DYNX(W_,80) = DYNX(W_,45);
DYNX(W_,81) = DYNX(W_,46);
DYNX(W_,82) = DYNX(W_,47);
DYNX(W_,83) = DYNX(W_,48);
DYNX(W_,84) = DYNX(W_,49);
DYNX(W_,99) = DYNX(W_,78);
DYNX(DYNhelp,3) = DYNX(W_,79)*DYNX(W_,79)+DYNX(W_,80)*DYNX(W_,80)+DYNX(W_,81)*
  DYNX(W_,81);
DYNX(DYNhelp,4) = DYNX(W_,82)*DYNX(W_,82);
DYNX(DYNhelp,5) = sqrtGuarded(DYNX(DYNhelp,3)+DYNX(DYNhelp,4)+DYNX(W_,83)*
  DYNX(W_,83)+DYNX(W_,84)*DYNX(W_,84),"system.miso[1].transferFunction[2].a[1]*system.miso[1].transferFunction[2].a[1]+system.miso[1].transferFunction[2].a[2]*system.miso[1].transferFunction[2].a[2]+system.miso[1].transferFunction[2].a[3]*system.miso[1].transferFunction[2].a[3]+system.miso[1].transferFunction[2].a[4]*system.miso[1].transferFunction[2].a[4]+system.miso[1].transferFunction[2].a[5]*system.miso[1].transferFunction[2].a[...");
DYNX(W_,101) = IF DYNX(W_,84) > 1E-013*DYNX(DYNhelp,5) THEN DYNX(W_,84) ELSE 1.0;
DYNX(W_,105) = DYNX(W_,50);
DYNX(W_,106) = DYNX(W_,51);
DYNX(W_,108) = DYNX(W_,5);
DYNX(W_,109) = DYNX(W_,6);
DYNX(W_,110) = DYNX(W_,19);
DYNX(W_,111) = DYNX(W_,20);
DYNX(W_,112) = DYNX(W_,21);
DYNX(W_,113) = DYNX(W_,22);
DYNX(W_,114) = DYNX(W_,23);
DYNX(W_,115) = DYNX(W_,24);
DYNX(W_,116) = DYNX(W_,25);
DYNX(W_,117) = DYNX(W_,26);
DYNX(W_,118) = DYNX(W_,27);
DYNX(W_,119) = DYNX(W_,28);
DYNX(W_,120) = DYNX(W_,29);
DYNX(W_,121) = DYNX(W_,30);
DYNX(W_,122) = DYNX(W_,33);
DYNX(W_,123) = DYNX(W_,34);
DYNX(W_,125) = DYNX(W_,108);
DYNX(W_,126) = DYNX(W_,110);
DYNX(W_,127) = DYNX(W_,111);
DYNX(W_,128) = DYNX(W_,112);
DYNX(W_,129) = DYNX(W_,113);
DYNX(W_,130) = DYNX(W_,114);
DYNX(W_,131) = DYNX(W_,115);
DYNX(W_,146) = DYNX(W_,125);
DYNX(DYNhelp,6) = DYNX(W_,126)*DYNX(W_,126)+DYNX(W_,127)*DYNX(W_,127)+
  DYNX(W_,128)*DYNX(W_,128);
DYNX(DYNhelp,7) = DYNX(W_,129)*DYNX(W_,129);
DYNX(DYNhelp,8) = sqrtGuarded(DYNX(DYNhelp,6)+DYNX(DYNhelp,7)+DYNX(W_,130)*
  DYNX(W_,130)+DYNX(W_,131)*DYNX(W_,131),"system.miso[2].transferFunction[1].a[1]*system.miso[2].transferFunction[1].a[1]+system.miso[2].transferFunction[1].a[2]*system.miso[2].transferFunction[1].a[2]+system.miso[2].transferFunction[1].a[3]*system.miso[2].transferFunction[1].a[3]+system.miso[2].transferFunction[1].a[4]*system.miso[2].transferFunction[1].a[4]+system.miso[2].transferFunction[1].a[5]*system.miso[2].transferFunction[1].a[...");
DYNX(W_,148) = IF DYNX(W_,131) > 1E-013*DYNX(DYNhelp,8) THEN DYNX(W_,131) ELSE 
  1.0;
DYNX(W_,150) = DYNX(W_,109);
DYNX(W_,151) = DYNX(W_,116);
DYNX(W_,152) = DYNX(W_,117);
DYNX(W_,153) = DYNX(W_,118);
DYNX(W_,154) = DYNX(W_,119);
DYNX(W_,155) = DYNX(W_,120);
DYNX(W_,156) = DYNX(W_,121);
DYNX(W_,171) = DYNX(W_,150);
DYNX(DYNhelp,9) = DYNX(W_,151)*DYNX(W_,151)+DYNX(W_,152)*DYNX(W_,152)+
  DYNX(W_,153)*DYNX(W_,153);
DYNX(DYNhelp,10) = DYNX(W_,154)*DYNX(W_,154);
DYNX(DYNhelp,11) = sqrtGuarded(DYNX(DYNhelp,9)+DYNX(DYNhelp,10)+DYNX(W_,155)*
  DYNX(W_,155)+DYNX(W_,156)*DYNX(W_,156),"system.miso[2].transferFunction[2].a[1]*system.miso[2].transferFunction[2].a[1]+system.miso[2].transferFunction[2].a[2]*system.miso[2].transferFunction[2].a[2]+system.miso[2].transferFunction[2].a[3]*system.miso[2].transferFunction[2].a[3]+system.miso[2].transferFunction[2].a[4]*system.miso[2].transferFunction[2].a[4]+system.miso[2].transferFunction[2].a[5]*system.miso[2].transferFunction[2].a[...");
DYNX(W_,173) = IF DYNX(W_,156) > 1E-013*DYNX(DYNhelp,11) THEN DYNX(W_,156) ELSE 
  1.0;
DYNX(W_,177) = DYNX(W_,122);
DYNX(W_,178) = DYNX(W_,123);
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,61) = DYNX(DP_,32);
DYNX(W_,62) = DYNX(DP_,33);
DYNX(W_,63) = DYNX(DP_,34);
DYNX(W_,64) = DYNX(DP_,35);
DYNX(W_,65) = DYNX(DP_,36);
DYNX(W_,86) = DYNX(DP_,38);
DYNX(W_,87) = DYNX(DP_,39);
DYNX(W_,88) = DYNX(DP_,40);
DYNX(W_,89) = DYNX(DP_,41);
DYNX(W_,90) = DYNX(DP_,42);
DYNX(W_,133) = DYNX(DP_,47);
DYNX(W_,134) = DYNX(DP_,48);
DYNX(W_,135) = DYNX(DP_,49);
DYNX(W_,136) = DYNX(DP_,50);
DYNX(W_,137) = DYNX(DP_,51);
DYNX(W_,158) = DYNX(DP_,53);
DYNX(W_,159) = DYNX(DP_,54);
DYNX(W_,160) = DYNX(DP_,55);
DYNX(W_,161) = DYNX(DP_,56);
DYNX(W_,162) = DYNX(DP_,57);
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(W_,3) = DYNX(DP_,0);
DYNX(W_,36) = DYNX(W_,3);
DYNX(W_,53) = DYNX(W_,36);
DYNX(W_,74) = DYNX(W_,53);
DYNX(W_,12) = DYNX(DP_,9);
DYNX(W_,43) = DYNX(W_,12);
DYNX(W_,59) = DYNX(W_,43);
DYNX(W_,7) = DYNX(DP_,4);
DYNX(W_,38) = DYNX(W_,7);
DYNX(W_,54) = DYNX(W_,38);
DYNX(W_,8) = DYNX(DP_,5);
DYNX(W_,39) = DYNX(W_,8);
DYNX(W_,55) = DYNX(W_,39);
DYNX(W_,9) = DYNX(DP_,6);
DYNX(W_,40) = DYNX(W_,9);
DYNX(W_,56) = DYNX(W_,40);
DYNX(W_,10) = DYNX(DP_,7);
DYNX(W_,41) = DYNX(W_,10);
DYNX(W_,57) = DYNX(W_,41);
DYNX(W_,11) = DYNX(DP_,8);
DYNX(W_,42) = DYNX(W_,11);
DYNX(W_,58) = DYNX(W_,42);
DYNX(W_,76) = IF DYNX(W_,59) > 1E-013*sqrtGuarded(DYNX(W_,54)*DYNX(W_,54)+
  DYNX(W_,55)*DYNX(W_,55)+DYNX(W_,56)*DYNX(W_,56)+DYNX(W_,57)*DYNX(W_,57)+
  DYNX(W_,58)*DYNX(W_,58)+DYNX(W_,59)*DYNX(W_,59),"system.miso[1].transferFunction[1].a[1]*system.miso[1].transferFunction[1].a[1]+system.miso[1].transferFunction[1].a[2]*system.miso[1].transferFunction[1].a[2]+system.miso[1].transferFunction[1].a[3]*system.miso[1].transferFunction[1].a[3]+system.miso[1].transferFunction[1].a[4]*system.miso[1].transferFunction[1].a[4]+system.miso[1].transferFunction[1].a[5]*system.miso[1].transferFunction[1].a[...")
   THEN DYNX(W_,59) ELSE 1.0;
DYNX(W_,52) = divmacro(DYNX(W_,74)*DYNX(X_,4),"system.miso[1].transferFunction[1].bb[6]*system.miso[1].transferFunction[1].x_scaled[5]",
  DYNX(W_,76),"system.miso[1].transferFunction[1].a_end");
DYNX(W_,31) = DYNX(DP_,28);
DYNX(W_,50) = DYNX(W_,31);
DYNX(W_,105) = DYNX(W_,50);
DYNX(W_,103) = delay(DYNX(W_,52), DYNX(W_,105), DYNX(W_,105), 0, 
  "delay(system.miso[1].transferFunction[1].y, system.miso[1].fixedDelay[1].delayTime)");
DYNX(W_,4) = DYNX(DP_,1);
DYNX(W_,37) = DYNX(W_,4);
DYNX(W_,78) = DYNX(W_,37);
DYNX(W_,99) = DYNX(W_,78);
DYNX(W_,18) = DYNX(DP_,15);
DYNX(W_,49) = DYNX(W_,18);
DYNX(W_,84) = DYNX(W_,49);
DYNX(W_,13) = DYNX(DP_,10);
DYNX(W_,44) = DYNX(W_,13);
DYNX(W_,79) = DYNX(W_,44);
DYNX(W_,14) = DYNX(DP_,11);
DYNX(W_,45) = DYNX(W_,14);
DYNX(W_,80) = DYNX(W_,45);
DYNX(W_,15) = DYNX(DP_,12);
DYNX(W_,46) = DYNX(W_,15);
DYNX(W_,81) = DYNX(W_,46);
DYNX(W_,16) = DYNX(DP_,13);
DYNX(W_,47) = DYNX(W_,16);
DYNX(W_,82) = DYNX(W_,47);
DYNX(W_,17) = DYNX(DP_,14);
DYNX(W_,48) = DYNX(W_,17);
DYNX(W_,83) = DYNX(W_,48);
DYNX(W_,101) = IF DYNX(W_,84) > 1E-013*sqrtGuarded(DYNX(W_,79)*DYNX(W_,79)+
  DYNX(W_,80)*DYNX(W_,80)+DYNX(W_,81)*DYNX(W_,81)+DYNX(W_,82)*DYNX(W_,82)+
  DYNX(W_,83)*DYNX(W_,83)+DYNX(W_,84)*DYNX(W_,84),"system.miso[1].transferFunction[2].a[1]*system.miso[1].transferFunction[2].a[1]+system.miso[1].transferFunction[2].a[2]*system.miso[1].transferFunction[2].a[2]+system.miso[1].transferFunction[2].a[3]*system.miso[1].transferFunction[2].a[3]+system.miso[1].transferFunction[2].a[4]*system.miso[1].transferFunction[2].a[4]+system.miso[1].transferFunction[2].a[5]*system.miso[1].transferFunction[2].a[...")
   THEN DYNX(W_,84) ELSE 1.0;
DYNX(W_,77) = divmacro(DYNX(W_,99)*DYNX(X_,9),"system.miso[1].transferFunction[2].bb[6]*system.miso[1].transferFunction[2].x_scaled[5]",
  DYNX(W_,101),"system.miso[1].transferFunction[2].a_end");
DYNX(W_,32) = DYNX(DP_,29);
DYNX(W_,51) = DYNX(W_,32);
DYNX(W_,106) = DYNX(W_,51);
DYNX(W_,104) = delay(DYNX(W_,77), DYNX(W_,106), DYNX(W_,106), 1, 
  "delay(system.miso[1].transferFunction[2].y, system.miso[1].fixedDelay[2].delayTime)");
DYNX(Y_,0) = DYNX(DP_,45)*DYNX(W_,103)+DYNX(DP_,46)*DYNX(W_,104);
DYNX(W_,5) = DYNX(DP_,2);
DYNX(W_,108) = DYNX(W_,5);
DYNX(W_,125) = DYNX(W_,108);
DYNX(W_,146) = DYNX(W_,125);
DYNX(W_,24) = DYNX(DP_,21);
DYNX(W_,115) = DYNX(W_,24);
DYNX(W_,131) = DYNX(W_,115);
DYNX(W_,19) = DYNX(DP_,16);
DYNX(W_,110) = DYNX(W_,19);
DYNX(W_,126) = DYNX(W_,110);
DYNX(W_,20) = DYNX(DP_,17);
DYNX(W_,111) = DYNX(W_,20);
DYNX(W_,127) = DYNX(W_,111);
DYNX(W_,21) = DYNX(DP_,18);
DYNX(W_,112) = DYNX(W_,21);
DYNX(W_,128) = DYNX(W_,112);
DYNX(W_,22) = DYNX(DP_,19);
DYNX(W_,113) = DYNX(W_,22);
DYNX(W_,129) = DYNX(W_,113);
DYNX(W_,23) = DYNX(DP_,20);
DYNX(W_,114) = DYNX(W_,23);
DYNX(W_,130) = DYNX(W_,114);
DYNX(W_,148) = IF DYNX(W_,131) > 1E-013*sqrtGuarded(DYNX(W_,126)*DYNX(W_,126)+
  DYNX(W_,127)*DYNX(W_,127)+DYNX(W_,128)*DYNX(W_,128)+DYNX(W_,129)*DYNX(W_,129)+
  DYNX(W_,130)*DYNX(W_,130)+DYNX(W_,131)*DYNX(W_,131),"system.miso[2].transferFunction[1].a[1]*system.miso[2].transferFunction[1].a[1]+system.miso[2].transferFunction[1].a[2]*system.miso[2].transferFunction[1].a[2]+system.miso[2].transferFunction[1].a[3]*system.miso[2].transferFunction[1].a[3]+system.miso[2].transferFunction[1].a[4]*system.miso[2].transferFunction[1].a[4]+system.miso[2].transferFunction[1].a[5]*system.miso[2].transferFunction[1].a[...")
   THEN DYNX(W_,131) ELSE 1.0;
DYNX(W_,124) = divmacro(DYNX(W_,146)*DYNX(X_,14),"system.miso[2].transferFunction[1].bb[6]*system.miso[2].transferFunction[1].x_scaled[5]",
  DYNX(W_,148),"system.miso[2].transferFunction[1].a_end");
DYNX(W_,33) = DYNX(DP_,30);
DYNX(W_,122) = DYNX(W_,33);
DYNX(W_,177) = DYNX(W_,122);
DYNX(W_,175) = delay(DYNX(W_,124), DYNX(W_,177), DYNX(W_,177), 2, 
  "delay(system.miso[2].transferFunction[1].y, system.miso[2].fixedDelay[1].delayTime)");
DYNX(W_,6) = DYNX(DP_,3);
DYNX(W_,109) = DYNX(W_,6);
BreakSectionFunctionCallNew(0);
BreakSectionFunctionEnd()
BreakSectionFunctionStart(1);
DYNX(W_,150) = DYNX(W_,109);
DYNX(W_,171) = DYNX(W_,150);
DYNX(W_,30) = DYNX(DP_,27);
DYNX(W_,121) = DYNX(W_,30);
DYNX(W_,156) = DYNX(W_,121);
DYNX(W_,25) = DYNX(DP_,22);
DYNX(W_,116) = DYNX(W_,25);
DYNX(W_,151) = DYNX(W_,116);
DYNX(W_,26) = DYNX(DP_,23);
DYNX(W_,117) = DYNX(W_,26);
DYNX(W_,152) = DYNX(W_,117);
DYNX(W_,27) = DYNX(DP_,24);
DYNX(W_,118) = DYNX(W_,27);
DYNX(W_,153) = DYNX(W_,118);
DYNX(W_,28) = DYNX(DP_,25);
DYNX(W_,119) = DYNX(W_,28);
DYNX(W_,154) = DYNX(W_,119);
DYNX(W_,29) = DYNX(DP_,26);
DYNX(W_,120) = DYNX(W_,29);
DYNX(W_,155) = DYNX(W_,120);
DYNX(W_,173) = IF DYNX(W_,156) > 1E-013*sqrtGuarded(DYNX(W_,151)*DYNX(W_,151)+
  DYNX(W_,152)*DYNX(W_,152)+DYNX(W_,153)*DYNX(W_,153)+DYNX(W_,154)*DYNX(W_,154)+
  DYNX(W_,155)*DYNX(W_,155)+DYNX(W_,156)*DYNX(W_,156),"system.miso[2].transferFunction[2].a[1]*system.miso[2].transferFunction[2].a[1]+system.miso[2].transferFunction[2].a[2]*system.miso[2].transferFunction[2].a[2]+system.miso[2].transferFunction[2].a[3]*system.miso[2].transferFunction[2].a[3]+system.miso[2].transferFunction[2].a[4]*system.miso[2].transferFunction[2].a[4]+system.miso[2].transferFunction[2].a[5]*system.miso[2].transferFunction[2].a[...")
   THEN DYNX(W_,156) ELSE 1.0;
DYNX(W_,149) = divmacro(DYNX(W_,171)*DYNX(X_,19),"system.miso[2].transferFunction[2].bb[6]*system.miso[2].transferFunction[2].x_scaled[5]",
  DYNX(W_,173),"system.miso[2].transferFunction[2].a_end");
DYNX(W_,34) = DYNX(DP_,31);
DYNX(W_,123) = DYNX(W_,34);
DYNX(W_,178) = DYNX(W_,123);
DYNX(W_,176) = delay(DYNX(W_,149), DYNX(W_,178), DYNX(W_,178), 3, 
  "delay(system.miso[2].transferFunction[2].y, system.miso[2].fixedDelay[2].delayTime)");
DYNX(Y_,1) = DYNX(DP_,60)*DYNX(W_,175)+DYNX(DP_,61)*DYNX(W_,176);
DYNX(F_,3) = DYNX(X_,2);
DYNX(F_,2) = DYNX(X_,1);
DYNX(F_,1) = DYNX(X_,0);
DYNX(F_,0) = divmacro(DYNX(W_,76)*DYNX(U_,0)-(DYNX(W_,55)*DYNX(X_,0)+DYNX(W_,56)
  *DYNX(X_,1)+DYNX(W_,57)*DYNX(X_,2)+DYNX(W_,58)*DYNX(X_,3)+DYNX(W_,59)*
  DYNX(X_,4)),"system.miso[1].transferFunction[1].a_end*u[1]-(system.miso[1].transferFunction[1].a[2]*system.miso[1].transferFunction[1].x_scaled[1]+system.miso[1].transferFunction[1].a[3]*system.miso[1].transferFunction[1].x_scaled[2]+system.miso[1].transferFunction[1].a[4]*system.miso[1].transferFunction[1].x_scaled[3]+system.miso[1].transferFunction[1].a[5]*system.miso[1].transferFunction[1].x_scaled[4]+sy...",
  DYNX(W_,54),"system.miso[1].transferFunction[1].a[1]");
DYNX(F_,4) = DYNX(X_,3);
DYNX(F_,8) = DYNX(X_,7);
DYNX(F_,7) = DYNX(X_,6);
DYNX(F_,6) = DYNX(X_,5);
DYNX(F_,5) = divmacro(DYNX(W_,101)*DYNX(U_,1)-(DYNX(W_,80)*DYNX(X_,5)+
  DYNX(W_,81)*DYNX(X_,6)+DYNX(W_,82)*DYNX(X_,7)+DYNX(W_,83)*DYNX(X_,8)+
  DYNX(W_,84)*DYNX(X_,9)),"system.miso[1].transferFunction[2].a_end*u[2]-(system.miso[1].transferFunction[2].a[2]*system.miso[1].transferFunction[2].x_scaled[1]+system.miso[1].transferFunction[2].a[3]*system.miso[1].transferFunction[2].x_scaled[2]+system.miso[1].transferFunction[2].a[4]*system.miso[1].transferFunction[2].x_scaled[3]+system.miso[1].transferFunction[2].a[5]*system.miso[1].transferFunction[2].x_scaled[4]+sy...",
  DYNX(W_,79),"system.miso[1].transferFunction[2].a[1]");
DYNX(F_,9) = DYNX(X_,8);
DYNX(F_,13) = DYNX(X_,12);
DYNX(F_,12) = DYNX(X_,11);
DYNX(F_,11) = DYNX(X_,10);
DYNX(F_,10) = divmacro(DYNX(W_,148)*DYNX(U_,0)-(DYNX(W_,127)*DYNX(X_,10)+
  DYNX(W_,128)*DYNX(X_,11)+DYNX(W_,129)*DYNX(X_,12)+DYNX(W_,130)*DYNX(X_,13)+
  DYNX(W_,131)*DYNX(X_,14)),"system.miso[2].transferFunction[1].a_end*u[1]-(system.miso[2].transferFunction[1].a[2]*system.miso[2].transferFunction[1].x_scaled[1]+system.miso[2].transferFunction[1].a[3]*system.miso[2].transferFunction[1].x_scaled[2]+system.miso[2].transferFunction[1].a[4]*system.miso[2].transferFunction[1].x_scaled[3]+system.miso[2].transferFunction[1].a[5]*system.miso[2].transferFunction[1].x_scaled[4]+sy...",
  DYNX(W_,126),"system.miso[2].transferFunction[1].a[1]");
DYNX(F_,14) = DYNX(X_,13);
DYNX(F_,18) = DYNX(X_,17);
DYNX(F_,17) = DYNX(X_,16);
DYNX(F_,16) = DYNX(X_,15);
DYNX(F_,15) = divmacro(DYNX(W_,173)*DYNX(U_,1)-(DYNX(W_,152)*DYNX(X_,15)+
  DYNX(W_,153)*DYNX(X_,16)+DYNX(W_,154)*DYNX(X_,17)+DYNX(W_,155)*DYNX(X_,18)+
  DYNX(W_,156)*DYNX(X_,19)),"system.miso[2].transferFunction[2].a_end*u[2]-(system.miso[2].transferFunction[2].a[2]*system.miso[2].transferFunction[2].x_scaled[1]+system.miso[2].transferFunction[2].a[3]*system.miso[2].transferFunction[2].x_scaled[2]+system.miso[2].transferFunction[2].a[4]*system.miso[2].transferFunction[2].x_scaled[3]+system.miso[2].transferFunction[2].a[5]*system.miso[2].transferFunction[2].x_scaled[4]+sy...",
  DYNX(W_,151),"system.miso[2].transferFunction[2].a[1]");
DYNX(F_,19) = DYNX(X_,18);
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(W_,52) = divmacro(DYNX(W_,74)*DYNX(X_,4),"system.miso[1].transferFunction[1].bb[6]*system.miso[1].transferFunction[1].x_scaled[5]",
  DYNX(W_,76),"system.miso[1].transferFunction[1].a_end");
DYNX(W_,103) = delay(DYNX(W_,52), DYNX(W_,105), DYNX(W_,105), 4, 
  "delay(system.miso[1].transferFunction[1].y, system.miso[1].fixedDelay[1].delayTime)");
DYNX(W_,77) = divmacro(DYNX(W_,99)*DYNX(X_,9),"system.miso[1].transferFunction[2].bb[6]*system.miso[1].transferFunction[2].x_scaled[5]",
  DYNX(W_,101),"system.miso[1].transferFunction[2].a_end");
DYNX(W_,104) = delay(DYNX(W_,77), DYNX(W_,106), DYNX(W_,106), 5, 
  "delay(system.miso[1].transferFunction[2].y, system.miso[1].fixedDelay[2].delayTime)");
DYNX(Y_,0) = DYNX(DP_,45)*DYNX(W_,103)+DYNX(DP_,46)*DYNX(W_,104);
DYNX(W_,124) = divmacro(DYNX(W_,146)*DYNX(X_,14),"system.miso[2].transferFunction[1].bb[6]*system.miso[2].transferFunction[1].x_scaled[5]",
  DYNX(W_,148),"system.miso[2].transferFunction[1].a_end");
DYNX(W_,175) = delay(DYNX(W_,124), DYNX(W_,177), DYNX(W_,177), 6, 
  "delay(system.miso[2].transferFunction[1].y, system.miso[2].fixedDelay[1].delayTime)");
DYNX(W_,149) = divmacro(DYNX(W_,171)*DYNX(X_,19),"system.miso[2].transferFunction[2].bb[6]*system.miso[2].transferFunction[2].x_scaled[5]",
  DYNX(W_,173),"system.miso[2].transferFunction[2].a_end");
DYNX(W_,176) = delay(DYNX(W_,149), DYNX(W_,178), DYNX(W_,178), 7, 
  "delay(system.miso[2].transferFunction[2].y, system.miso[2].fixedDelay[2].delayTime)");
DYNX(Y_,1) = DYNX(DP_,60)*DYNX(W_,175)+DYNX(DP_,61)*DYNX(W_,176);

DynamicsSection
DYNX(F_,3) = DYNX(X_,2);
DYNX(F_,2) = DYNX(X_,1);
DYNX(F_,1) = DYNX(X_,0);
DYNX(F_,0) = divmacro(DYNX(W_,76)*DYNX(U_,0)-(DYNX(W_,55)*DYNX(X_,0)+DYNX(W_,56)
  *DYNX(X_,1)+DYNX(W_,57)*DYNX(X_,2)+DYNX(W_,58)*DYNX(X_,3)+DYNX(W_,59)*
  DYNX(X_,4)),"system.miso[1].transferFunction[1].a_end*u[1]-(system.miso[1].transferFunction[1].a[2]*system.miso[1].transferFunction[1].x_scaled[1]+system.miso[1].transferFunction[1].a[3]*system.miso[1].transferFunction[1].x_scaled[2]+system.miso[1].transferFunction[1].a[4]*system.miso[1].transferFunction[1].x_scaled[3]+system.miso[1].transferFunction[1].a[5]*system.miso[1].transferFunction[1].x_scaled[4]+sy...",
  DYNX(W_,54),"system.miso[1].transferFunction[1].a[1]");
DYNX(F_,4) = DYNX(X_,3);
DYNX(F_,8) = DYNX(X_,7);
DYNX(F_,7) = DYNX(X_,6);
DYNX(F_,6) = DYNX(X_,5);
DYNX(F_,5) = divmacro(DYNX(W_,101)*DYNX(U_,1)-(DYNX(W_,80)*DYNX(X_,5)+
  DYNX(W_,81)*DYNX(X_,6)+DYNX(W_,82)*DYNX(X_,7)+DYNX(W_,83)*DYNX(X_,8)+
  DYNX(W_,84)*DYNX(X_,9)),"system.miso[1].transferFunction[2].a_end*u[2]-(system.miso[1].transferFunction[2].a[2]*system.miso[1].transferFunction[2].x_scaled[1]+system.miso[1].transferFunction[2].a[3]*system.miso[1].transferFunction[2].x_scaled[2]+system.miso[1].transferFunction[2].a[4]*system.miso[1].transferFunction[2].x_scaled[3]+system.miso[1].transferFunction[2].a[5]*system.miso[1].transferFunction[2].x_scaled[4]+sy...",
  DYNX(W_,79),"system.miso[1].transferFunction[2].a[1]");
DYNX(F_,9) = DYNX(X_,8);
DYNX(F_,13) = DYNX(X_,12);
DYNX(F_,12) = DYNX(X_,11);
DYNX(F_,11) = DYNX(X_,10);
DYNX(F_,10) = divmacro(DYNX(W_,148)*DYNX(U_,0)-(DYNX(W_,127)*DYNX(X_,10)+
  DYNX(W_,128)*DYNX(X_,11)+DYNX(W_,129)*DYNX(X_,12)+DYNX(W_,130)*DYNX(X_,13)+
  DYNX(W_,131)*DYNX(X_,14)),"system.miso[2].transferFunction[1].a_end*u[1]-(system.miso[2].transferFunction[1].a[2]*system.miso[2].transferFunction[1].x_scaled[1]+system.miso[2].transferFunction[1].a[3]*system.miso[2].transferFunction[1].x_scaled[2]+system.miso[2].transferFunction[1].a[4]*system.miso[2].transferFunction[1].x_scaled[3]+system.miso[2].transferFunction[1].a[5]*system.miso[2].transferFunction[1].x_scaled[4]+sy...",
  DYNX(W_,126),"system.miso[2].transferFunction[1].a[1]");
DYNX(F_,14) = DYNX(X_,13);
DYNX(F_,18) = DYNX(X_,17);
DYNX(F_,17) = DYNX(X_,16);
DYNX(F_,16) = DYNX(X_,15);
DYNX(F_,15) = divmacro(DYNX(W_,173)*DYNX(U_,1)-(DYNX(W_,152)*DYNX(X_,15)+
  DYNX(W_,153)*DYNX(X_,16)+DYNX(W_,154)*DYNX(X_,17)+DYNX(W_,155)*DYNX(X_,18)+
  DYNX(W_,156)*DYNX(X_,19)),"system.miso[2].transferFunction[2].a_end*u[2]-(system.miso[2].transferFunction[2].a[2]*system.miso[2].transferFunction[2].x_scaled[1]+system.miso[2].transferFunction[2].a[3]*system.miso[2].transferFunction[2].x_scaled[2]+system.miso[2].transferFunction[2].a[4]*system.miso[2].transferFunction[2].x_scaled[3]+system.miso[2].transferFunction[2].a[5]*system.miso[2].transferFunction[2].x_scaled[4]+sy...",
  DYNX(W_,151),"system.miso[2].transferFunction[2].a[1]");
DYNX(F_,19) = DYNX(X_,18);

AcceptedSection1

AcceptedSection2
DYNX(W_,61) = divmacro(DYNX(X_,0),"system.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,76),"system.miso[1].transferFunction[1].a_end");
DYNX(W_,62) = divmacro(DYNX(X_,1),"system.miso[1].transferFunction[1].x_scaled[2]",
  DYNX(W_,76),"system.miso[1].transferFunction[1].a_end");
DYNX(W_,63) = divmacro(DYNX(X_,2),"system.miso[1].transferFunction[1].x_scaled[3]",
  DYNX(W_,76),"system.miso[1].transferFunction[1].a_end");
DYNX(W_,64) = divmacro(DYNX(X_,3),"system.miso[1].transferFunction[1].x_scaled[4]",
  DYNX(W_,76),"system.miso[1].transferFunction[1].a_end");
DYNX(W_,65) = divmacro(DYNX(X_,4),"system.miso[1].transferFunction[1].x_scaled[5]",
  DYNX(W_,76),"system.miso[1].transferFunction[1].a_end");
DYNX(W_,86) = divmacro(DYNX(X_,5),"system.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,101),"system.miso[1].transferFunction[2].a_end");
DYNX(W_,87) = divmacro(DYNX(X_,6),"system.miso[1].transferFunction[2].x_scaled[2]",
  DYNX(W_,101),"system.miso[1].transferFunction[2].a_end");
DYNX(W_,88) = divmacro(DYNX(X_,7),"system.miso[1].transferFunction[2].x_scaled[3]",
  DYNX(W_,101),"system.miso[1].transferFunction[2].a_end");
DYNX(W_,89) = divmacro(DYNX(X_,8),"system.miso[1].transferFunction[2].x_scaled[4]",
  DYNX(W_,101),"system.miso[1].transferFunction[2].a_end");
DYNX(W_,90) = divmacro(DYNX(X_,9),"system.miso[1].transferFunction[2].x_scaled[5]",
  DYNX(W_,101),"system.miso[1].transferFunction[2].a_end");
DYNX(W_,133) = divmacro(DYNX(X_,10),"system.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,148),"system.miso[2].transferFunction[1].a_end");
DYNX(W_,134) = divmacro(DYNX(X_,11),"system.miso[2].transferFunction[1].x_scaled[2]",
  DYNX(W_,148),"system.miso[2].transferFunction[1].a_end");
DYNX(W_,135) = divmacro(DYNX(X_,12),"system.miso[2].transferFunction[1].x_scaled[3]",
  DYNX(W_,148),"system.miso[2].transferFunction[1].a_end");
DYNX(W_,136) = divmacro(DYNX(X_,13),"system.miso[2].transferFunction[1].x_scaled[4]",
  DYNX(W_,148),"system.miso[2].transferFunction[1].a_end");
DYNX(W_,137) = divmacro(DYNX(X_,14),"system.miso[2].transferFunction[1].x_scaled[5]",
  DYNX(W_,148),"system.miso[2].transferFunction[1].a_end");
DYNX(W_,158) = divmacro(DYNX(X_,15),"system.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,173),"system.miso[2].transferFunction[2].a_end");
DYNX(W_,159) = divmacro(DYNX(X_,16),"system.miso[2].transferFunction[2].x_scaled[2]",
  DYNX(W_,173),"system.miso[2].transferFunction[2].a_end");
DYNX(W_,160) = divmacro(DYNX(X_,17),"system.miso[2].transferFunction[2].x_scaled[3]",
  DYNX(W_,173),"system.miso[2].transferFunction[2].a_end");
DYNX(W_,161) = divmacro(DYNX(X_,18),"system.miso[2].transferFunction[2].x_scaled[4]",
  DYNX(W_,173),"system.miso[2].transferFunction[2].a_end");
DYNX(W_,162) = divmacro(DYNX(X_,19),"system.miso[2].transferFunction[2].x_scaled[5]",
  DYNX(W_,173),"system.miso[2].transferFunction[2].a_end");

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("n", "Number of in- and outputs [:#(type=Integer)]", 2, 0.0,0.0,\
0.0,0,517)
DeclareVariable("o", "Order of the Process = Degree -1 -> PT1 = 2 [:#(type=Integer)]",\
 6, 0.0,0.0,0.0,0,517)
DeclareParameter("num[1, 1, 1]", "Numerator of the system", 0, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("num[1, 2, 1]", "Numerator of the system", 1, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("num[2, 1, 1]", "Numerator of the system", 2, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("num[2, 2, 1]", "Numerator of the system", 3, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 1, 1]", "Denominator of the system", 4, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 1, 2]", "Denominator of the system", 5, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 1, 3]", "Denominator of the system", 6, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 1, 4]", "Denominator of the system", 7, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 1, 5]", "Denominator of the system", 8, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 1, 6]", "Denominator of the system", 9, 0.001, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 2, 1]", "Denominator of the system", 10, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 2, 2]", "Denominator of the system", 11, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 2, 3]", "Denominator of the system", 12, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 2, 4]", "Denominator of the system", 13, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 2, 5]", "Denominator of the system", 14, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 2, 6]", "Denominator of the system", 15, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 1]", "Denominator of the system", 16, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 2]", "Denominator of the system", 17, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 3]", "Denominator of the system", 18, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 4]", "Denominator of the system", 19, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 5]", "Denominator of the system", 20, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 6]", "Denominator of the system", 21, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 1]", "Denominator of the system", 22, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 2]", "Denominator of the system", 23, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 3]", "Denominator of the system", 24, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 4]", "Denominator of the system", 25, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 5]", "Denominator of the system", 26, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 6]", "Denominator of the system", 27, 0.001, \
0.0,0.0,0.0,0,560)
DeclareParameter("delay[1, 1]", "Delay of the system for every transfer function",\
 28, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("delay[1, 2]", "Delay of the system for every transfer function",\
 29, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("delay[2, 1]", "Delay of the system for every transfer function",\
 30, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("delay[2, 2]", "Delay of the system for every transfer function",\
 31, 0, 0.0,0.0,0.0,0,560)
DeclareInput("u[1]", "Systems set point [:#(prefix=input)]", 0, 0.0, 0.0,0.0,0.0,\
0,512)
DeclareInput("u[2]", "Systems set point [:#(prefix=input)]", 1, 0.0, 0.0,0.0,0.0,\
0,512)
DeclareOutput("y[1]", "Systems real output", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("y[2]", "Systems real output", 1, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.n", "Number of inputs (= number of outputs) [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("system.num[1, 1, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("system.num[1, 2, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("system.num[2, 1, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("system.num[2, 2, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("system.den[1, 1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 1, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 1, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 1, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 1, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 2, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 2, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 2, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[1, 2, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 1, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 1, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 1, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 1, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 2, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 2, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 2, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.den[2, 2, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.delay[1, 1]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.delay[1, 2]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.delay[2, 1]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.delay[2, 2]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("system.u[1]", "Connector of Real input signals", "u[1]", 1, 2, 0,\
 0)
DeclareAlias2("system.u[2]", "Connector of Real input signals", "u[2]", 1, 2, 1,\
 0)
DeclareAlias2("system.y[1]", "Connector of Real output signals", "y[1]", 1, 3, 0,\
 0)
DeclareAlias2("system.y[2]", "Connector of Real output signals", "y[2]", 1, 3, 1,\
 0)
DeclareVariable("system.miso[1].n", "Number of inputs [:#(type=Integer)]", 2, \
0.0,0.0,0.0,0,517)
DeclareVariable("system.miso[1].num[1, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].num[2, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[1, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[1, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[1, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[1, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[2, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[2, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[2, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].den[2, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].delay[1]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("system.miso[1].delay[2]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("system.miso[1].u[1]", "Connector of Real input signals", "u[1]", 1,\
 2, 0, 0)
DeclareAlias2("system.miso[1].u[2]", "Connector of Real input signals", "u[2]", 1,\
 2, 1, 0)
DeclareAlias2("system.miso[1].y", "Connector of Real output signal", "y[1]", 1, 3,\
 0, 0)
DeclareAlias2("system.miso[1].transferFunction[1].u", "Connector of Real input signal",\
 "u[1]", 1, 2, 0, 0)
DeclareVariable("system.miso[1].transferFunction[1].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[1].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[1].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[1].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[1].a[3]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[1].a[4]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[1].a[5]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[1].a[6]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[1].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 1, 1.0,4.0,0.0,0,517)
DeclareParameter("system.miso[1].transferFunction[1].x_start[1]", \
"Initial or guess values of states", 32, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[1].x_start[2]", \
"Initial or guess values of states", 33, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[1].x_start[3]", \
"Initial or guess values of states", 34, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[1].x_start[4]", \
"Initial or guess values of states", 35, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[1].x_start[5]", \
"Initial or guess values of states", 36, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[1].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 37, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("system.miso[1].transferFunction[1].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[1].x[2]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[1].x[3]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[1].x[4]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[1].x[5]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[1].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 6, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[1].transferFunction[1].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[1].transferFunction[1].nx", "[:#(type=Integer)]", 5,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[1].transferFunction[1].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[1].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[1].bb[3]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[1].bb[4]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[1].bb[5]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[1].bb[6]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[1].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("system.miso[1].transferFunction[1].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("system.miso[1].transferFunction[1].x_scaled[1]", "Scaled vector x",\
 0, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[1].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[1].x_scaled[2]", "Scaled vector x",\
 1, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[1].der(x_scaled[2])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[1].x_scaled[3]", "Scaled vector x",\
 2, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[1].der(x_scaled[3])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[1].x_scaled[4]", "Scaled vector x",\
 3, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[1].der(x_scaled[4])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[1].x_scaled[5]", "Scaled vector x",\
 4, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[1].der(x_scaled[5])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("system.miso[1].transferFunction[2].u", "Connector of Real input signal",\
 "u[2]", 1, 2, 1, 0)
DeclareVariable("system.miso[1].transferFunction[2].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[2].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[2].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[2].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[2].a[3]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[2].a[4]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[2].a[5]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[2].a[6]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[1].transferFunction[2].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 1, 1.0,4.0,0.0,0,517)
DeclareParameter("system.miso[1].transferFunction[2].x_start[1]", \
"Initial or guess values of states", 38, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[2].x_start[2]", \
"Initial or guess values of states", 39, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[2].x_start[3]", \
"Initial or guess values of states", 40, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[2].x_start[4]", \
"Initial or guess values of states", 41, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[2].x_start[5]", \
"Initial or guess values of states", 42, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].transferFunction[2].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 43, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("system.miso[1].transferFunction[2].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[2].x[2]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[2].x[3]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[2].x[4]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[2].x[5]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].transferFunction[2].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 6, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[1].transferFunction[2].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[1].transferFunction[2].nx", "[:#(type=Integer)]", 5,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[1].transferFunction[2].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[2].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[2].bb[3]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[2].bb[4]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[2].bb[5]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[2].bb[6]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[1].transferFunction[2].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("system.miso[1].transferFunction[2].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("system.miso[1].transferFunction[2].x_scaled[1]", "Scaled vector x",\
 5, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[2].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[2].x_scaled[2]", "Scaled vector x",\
 6, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[2].der(x_scaled[2])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[2].x_scaled[3]", "Scaled vector x",\
 7, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[2].der(x_scaled[3])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[2].x_scaled[4]", "Scaled vector x",\
 8, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[2].der(x_scaled[4])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[1].transferFunction[2].x_scaled[5]", "Scaled vector x",\
 9, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[1].transferFunction[2].der(x_scaled[5])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("system.miso[1].add.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 44, 5, 1.0,1E+100,0.0,0,564)
DeclareVariable("system.miso[1].add.nu", "Number of input connections [:#(type=Integer)]",\
 2, 0.0,1E+100,0.0,0,1541)
DeclareVariable("system.miso[1].add.u[1]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[1].add.u[2]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("system.miso[1].add.y", "", "y[1]", 1, 3, 0, 0)
DeclareParameter("system.miso[1].add.k[1]", "Input gains", 45, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[1].add.k[2]", "Input gains", 46, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("system.miso[1].fixedDelay[1].u", "Connector of Real input signal",\
 "system.miso[1].transferFunction[1].y", 1, 5, 52, 0)
DeclareAlias2("system.miso[1].fixedDelay[1].y", "Connector of Real output signal",\
 "system.miso[1].add.u[1]", 1, 5, 103, 0)
DeclareVariable("system.miso[1].fixedDelay[1].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("system.miso[1].fixedDelay[2].u", "Connector of Real input signal",\
 "system.miso[1].transferFunction[2].y", 1, 5, 77, 0)
DeclareAlias2("system.miso[1].fixedDelay[2].y", "Connector of Real output signal",\
 "system.miso[1].add.u[2]", 1, 5, 104, 0)
DeclareVariable("system.miso[1].fixedDelay[2].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].n", "Number of inputs [:#(type=Integer)]", 2, \
0.0,0.0,0.0,0,517)
DeclareVariable("system.miso[2].num[1, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].num[2, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[1, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[1, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[1, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[1, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[2, 3]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[2, 4]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[2, 5]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].den[2, 6]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].delay[1]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("system.miso[2].delay[2]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("system.miso[2].u[1]", "Connector of Real input signals", "u[1]", 1,\
 2, 0, 0)
DeclareAlias2("system.miso[2].u[2]", "Connector of Real input signals", "u[2]", 1,\
 2, 1, 0)
DeclareAlias2("system.miso[2].y", "Connector of Real output signal", "y[2]", 1, 3,\
 1, 0)
DeclareAlias2("system.miso[2].transferFunction[1].u", "Connector of Real input signal",\
 "u[1]", 1, 2, 0, 0)
DeclareVariable("system.miso[2].transferFunction[1].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[1].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[1].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[1].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[1].a[3]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[1].a[4]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[1].a[5]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[1].a[6]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[1].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 1, 1.0,4.0,0.0,0,517)
DeclareParameter("system.miso[2].transferFunction[1].x_start[1]", \
"Initial or guess values of states", 47, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[1].x_start[2]", \
"Initial or guess values of states", 48, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[1].x_start[3]", \
"Initial or guess values of states", 49, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[1].x_start[4]", \
"Initial or guess values of states", 50, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[1].x_start[5]", \
"Initial or guess values of states", 51, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[1].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 52, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("system.miso[2].transferFunction[1].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[1].x[2]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[1].x[3]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[1].x[4]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[1].x[5]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[1].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 6, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[2].transferFunction[1].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[2].transferFunction[1].nx", "[:#(type=Integer)]", 5,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[2].transferFunction[1].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[1].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[1].bb[3]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[1].bb[4]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[1].bb[5]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[1].bb[6]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[1].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("system.miso[2].transferFunction[1].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("system.miso[2].transferFunction[1].x_scaled[1]", "Scaled vector x",\
 10, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[1].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[1].x_scaled[2]", "Scaled vector x",\
 11, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[1].der(x_scaled[2])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[1].x_scaled[3]", "Scaled vector x",\
 12, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[1].der(x_scaled[3])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[1].x_scaled[4]", "Scaled vector x",\
 13, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[1].der(x_scaled[4])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[1].x_scaled[5]", "Scaled vector x",\
 14, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[1].der(x_scaled[5])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("system.miso[2].transferFunction[2].u", "Connector of Real input signal",\
 "u[2]", 1, 2, 1, 0)
DeclareVariable("system.miso[2].transferFunction[2].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[2].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[2].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[2].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[2].a[3]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[2].a[4]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[2].a[5]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[2].a[6]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("system.miso[2].transferFunction[2].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 1, 1.0,4.0,0.0,0,517)
DeclareParameter("system.miso[2].transferFunction[2].x_start[1]", \
"Initial or guess values of states", 53, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[2].x_start[2]", \
"Initial or guess values of states", 54, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[2].x_start[3]", \
"Initial or guess values of states", 55, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[2].x_start[4]", \
"Initial or guess values of states", 56, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[2].x_start[5]", \
"Initial or guess values of states", 57, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].transferFunction[2].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 58, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("system.miso[2].transferFunction[2].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[2].x[2]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[2].x[3]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[2].x[4]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[2].x[5]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].transferFunction[2].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 6, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[2].transferFunction[2].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[2].transferFunction[2].nx", "[:#(type=Integer)]", 5,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("system.miso[2].transferFunction[2].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[2].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[2].bb[3]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[2].bb[4]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[2].bb[5]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[2].bb[6]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("system.miso[2].transferFunction[2].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("system.miso[2].transferFunction[2].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("system.miso[2].transferFunction[2].x_scaled[1]", "Scaled vector x",\
 15, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[2].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[2].x_scaled[2]", "Scaled vector x",\
 16, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[2].der(x_scaled[2])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[2].x_scaled[3]", "Scaled vector x",\
 17, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[2].der(x_scaled[3])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[2].x_scaled[4]", "Scaled vector x",\
 18, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[2].der(x_scaled[4])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("system.miso[2].transferFunction[2].x_scaled[5]", "Scaled vector x",\
 19, 0.0, 0.0,0.0,0.0,0,2608)
DeclareDerivative("system.miso[2].transferFunction[2].der(x_scaled[5])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("system.miso[2].add.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 59, 5, 1.0,1E+100,0.0,0,564)
DeclareVariable("system.miso[2].add.nu", "Number of input connections [:#(type=Integer)]",\
 2, 0.0,1E+100,0.0,0,1541)
DeclareVariable("system.miso[2].add.u[1]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("system.miso[2].add.u[2]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("system.miso[2].add.y", "", "y[2]", 1, 3, 1, 0)
DeclareParameter("system.miso[2].add.k[1]", "Input gains", 60, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("system.miso[2].add.k[2]", "Input gains", 61, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("system.miso[2].fixedDelay[1].u", "Connector of Real input signal",\
 "system.miso[2].transferFunction[1].y", 1, 5, 124, 0)
DeclareAlias2("system.miso[2].fixedDelay[1].y", "Connector of Real output signal",\
 "system.miso[2].add.u[1]", 1, 5, 175, 0)
DeclareVariable("system.miso[2].fixedDelay[1].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("system.miso[2].fixedDelay[2].u", "Connector of Real input signal",\
 "system.miso[2].transferFunction[2].y", 1, 5, 149, 0)
DeclareAlias2("system.miso[2].fixedDelay[2].y", "Connector of Real output signal",\
 "system.miso[2].add.u[2]", 1, 5, 176, 0)
DeclareVariable("system.miso[2].fixedDelay[2].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock

BreakSectionFunctionStart(0);
BreakSectionFunctionCallNew(1);
BreakSectionFunctionEnd()
