/* DSblock model generated by Dymola from Modelica model Masterthesis.Testers.Test_MIMOTF
 Dymola Version 2017 FD01 (64-bit), 2016-10-11 translated this at Fri Sep 01 11:33:09 2017

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    9
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    184
#define NP_    75
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 974965634
#define NHash2_ 460760560
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  3
#define NSamp_ 0
#define NCons_ 0
#define NA_    45
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 9
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 18
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Masterthesis.Testers.Test_MIMOTF";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/juliu/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[11]={1 , 9 , 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9};
DYMOLA_STATIC int QJacobianGC_[10]={
1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 0};
DYMOLA_STATIC double QJacobianCD_[10]={0  , 44 , 55 , 66 , 77 , 88 , 99 , 110 , 121
   , 132};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 3;
DYNX(W_,7) = 3;
DYNX(W_,26) = 2;
DYNX(W_,27) = 1;
DYNX(W_,28) = 1;
DYNX(W_,39) = 2;
DYNX(W_,40) = 1;
DYNX(W_,41) = 1;
DYNX(W_,52) = 2;
DYNX(W_,53) = 1;
DYNX(W_,54) = 1;
DYNX(W_,59) = 3;
DYNX(W_,66) = 3;
DYNX(W_,85) = 2;
DYNX(W_,86) = 1;
DYNX(W_,87) = 1;
DYNX(W_,98) = 2;
DYNX(W_,99) = 1;
DYNX(W_,100) = 1;
DYNX(W_,111) = 2;
DYNX(W_,112) = 1;
DYNX(W_,113) = 1;
DYNX(W_,118) = 3;
DYNX(W_,125) = 3;
DYNX(W_,144) = 2;
DYNX(W_,145) = 1;
DYNX(W_,146) = 1;
DYNX(W_,157) = 2;
DYNX(W_,158) = 1;
DYNX(W_,159) = 1;
DYNX(W_,170) = 2;
DYNX(W_,171) = 1;
DYNX(W_,172) = 1;
DYNX(W_,177) = 3;
DYNX(W_,24) = 4;
DYNX(W_,29) = 0.0;
DYNX(W_,31) = 0.0;
DYNX(W_,37) = 4;
DYNX(W_,42) = 0.0;
DYNX(W_,44) = 0.0;
DYNX(W_,50) = 4;
DYNX(W_,55) = 0.0;
DYNX(W_,57) = 0.0;
DYNX(W_,83) = 4;
DYNX(W_,88) = 0.0;
DYNX(W_,90) = 0.0;
DYNX(W_,96) = 4;
DYNX(W_,101) = 0.0;
DYNX(W_,103) = 0.0;
DYNX(W_,109) = 4;
DYNX(W_,114) = 0.0;
DYNX(W_,116) = 0.0;
DYNX(W_,142) = 4;
DYNX(W_,147) = 0.0;
DYNX(W_,149) = 0.0;
DYNX(W_,155) = 4;
DYNX(W_,160) = 0.0;
DYNX(W_,162) = 0.0;
DYNX(W_,168) = 4;
DYNX(W_,173) = 0.0;
DYNX(W_,175) = 0.0;
#endif
BoundParameterSection
DYNX(W_,8) = DYNX(DP_,0);
DYNX(W_,9) = DYNX(DP_,1);
DYNX(W_,10) = DYNX(DP_,2);
DYNX(W_,11) = DYNX(DP_,9);
DYNX(W_,12) = DYNX(DP_,10);
DYNX(W_,13) = DYNX(DP_,11);
DYNX(W_,14) = DYNX(DP_,12);
DYNX(W_,15) = DYNX(DP_,13);
DYNX(W_,16) = DYNX(DP_,14);
DYNX(W_,17) = DYNX(DP_,27);
DYNX(W_,18) = DYNX(DP_,28);
DYNX(W_,19) = DYNX(DP_,29);
DYNX(W_,21) = DYNX(W_,8);
DYNX(W_,22) = DYNX(W_,11);
DYNX(W_,23) = DYNX(W_,12);
DYNX(W_,30) = DYNX(W_,21);
DYNX(DYNhelp,0) = sqrtGuarded(DYNX(W_,22)*DYNX(W_,22)+DYNX(W_,23)*DYNX(W_,23),
  "mimo_transferfunction1.miso[1].transferFunction[1].a[1]*mimo_transferfunction1.miso[1].transferFunction[1].a[1]+mimo_transferfunction1.miso[1].transferFunction[1].a[2]*mimo_transferfunction1.miso[1].transferFunction[1].a[2]");
DYNX(W_,32) = IF DYNX(W_,23) > 1E-013*DYNX(DYNhelp,0) THEN DYNX(W_,23) ELSE 1.0;
DYNX(W_,34) = DYNX(W_,9);
DYNX(W_,35) = DYNX(W_,13);
DYNX(W_,36) = DYNX(W_,14);
DYNX(W_,43) = DYNX(W_,34);
DYNX(DYNhelp,1) = sqrtGuarded(DYNX(W_,35)*DYNX(W_,35)+DYNX(W_,36)*DYNX(W_,36),
  "mimo_transferfunction1.miso[1].transferFunction[2].a[1]*mimo_transferfunction1.miso[1].transferFunction[2].a[1]+mimo_transferfunction1.miso[1].transferFunction[2].a[2]*mimo_transferfunction1.miso[1].transferFunction[2].a[2]");
DYNX(W_,45) = IF DYNX(W_,36) > 1E-013*DYNX(DYNhelp,1) THEN DYNX(W_,36) ELSE 1.0;
DYNX(W_,47) = DYNX(W_,10);
DYNX(W_,48) = DYNX(W_,15);
DYNX(W_,49) = DYNX(W_,16);
DYNX(W_,56) = DYNX(W_,47);
DYNX(DYNhelp,2) = sqrtGuarded(DYNX(W_,48)*DYNX(W_,48)+DYNX(W_,49)*DYNX(W_,49),
  "mimo_transferfunction1.miso[1].transferFunction[3].a[1]*mimo_transferfunction1.miso[1].transferFunction[3].a[1]+mimo_transferfunction1.miso[1].transferFunction[3].a[2]*mimo_transferfunction1.miso[1].transferFunction[3].a[2]");
DYNX(W_,58) = IF DYNX(W_,49) > 1E-013*DYNX(DYNhelp,2) THEN DYNX(W_,49) ELSE 1.0;
DYNX(W_,63) = DYNX(W_,17);
DYNX(W_,64) = DYNX(W_,18);
DYNX(W_,65) = DYNX(W_,19);
DYNX(W_,67) = DYNX(DP_,3);
DYNX(W_,68) = DYNX(DP_,4);
DYNX(W_,69) = DYNX(DP_,5);
DYNX(W_,70) = DYNX(DP_,15);
DYNX(W_,71) = DYNX(DP_,16);
DYNX(W_,72) = DYNX(DP_,17);
DYNX(W_,73) = DYNX(DP_,18);
DYNX(W_,74) = DYNX(DP_,19);
DYNX(W_,75) = DYNX(DP_,20);
DYNX(W_,76) = DYNX(DP_,30);
DYNX(W_,77) = DYNX(DP_,31);
DYNX(W_,78) = DYNX(DP_,32);
DYNX(W_,80) = DYNX(W_,67);
DYNX(W_,81) = DYNX(W_,70);
DYNX(W_,82) = DYNX(W_,71);
DYNX(W_,89) = DYNX(W_,80);
DYNX(DYNhelp,3) = sqrtGuarded(DYNX(W_,81)*DYNX(W_,81)+DYNX(W_,82)*DYNX(W_,82),
  "mimo_transferfunction1.miso[2].transferFunction[1].a[1]*mimo_transferfunction1.miso[2].transferFunction[1].a[1]+mimo_transferfunction1.miso[2].transferFunction[1].a[2]*mimo_transferfunction1.miso[2].transferFunction[1].a[2]");
DYNX(W_,91) = IF DYNX(W_,82) > 1E-013*DYNX(DYNhelp,3) THEN DYNX(W_,82) ELSE 1.0;
DYNX(W_,93) = DYNX(W_,68);
DYNX(W_,94) = DYNX(W_,72);
DYNX(W_,95) = DYNX(W_,73);
DYNX(W_,102) = DYNX(W_,93);
DYNX(DYNhelp,4) = sqrtGuarded(DYNX(W_,94)*DYNX(W_,94)+DYNX(W_,95)*DYNX(W_,95),
  "mimo_transferfunction1.miso[2].transferFunction[2].a[1]*mimo_transferfunction1.miso[2].transferFunction[2].a[1]+mimo_transferfunction1.miso[2].transferFunction[2].a[2]*mimo_transferfunction1.miso[2].transferFunction[2].a[2]");
DYNX(W_,104) = IF DYNX(W_,95) > 1E-013*DYNX(DYNhelp,4) THEN DYNX(W_,95) ELSE 1.0;
DYNX(W_,106) = DYNX(W_,69);
DYNX(W_,107) = DYNX(W_,74);
DYNX(W_,108) = DYNX(W_,75);
DYNX(W_,115) = DYNX(W_,106);
DYNX(DYNhelp,5) = sqrtGuarded(DYNX(W_,107)*DYNX(W_,107)+DYNX(W_,108)*
  DYNX(W_,108),"mimo_transferfunction1.miso[2].transferFunction[3].a[1]*mimo_transferfunction1.miso[2].transferFunction[3].a[1]+mimo_transferfunction1.miso[2].transferFunction[3].a[2]*mimo_transferfunction1.miso[2].transferFunction[3].a[2]");
DYNX(W_,117) = IF DYNX(W_,108) > 1E-013*DYNX(DYNhelp,5) THEN DYNX(W_,108) ELSE 
  1.0;
DYNX(W_,122) = DYNX(W_,76);
DYNX(W_,123) = DYNX(W_,77);
DYNX(W_,124) = DYNX(W_,78);
DYNX(W_,126) = DYNX(DP_,6);
DYNX(W_,127) = DYNX(DP_,7);
DYNX(W_,128) = DYNX(DP_,8);
DYNX(W_,129) = DYNX(DP_,21);
DYNX(W_,130) = DYNX(DP_,22);
DYNX(W_,131) = DYNX(DP_,23);
DYNX(W_,132) = DYNX(DP_,24);
DYNX(W_,133) = DYNX(DP_,25);
DYNX(W_,134) = DYNX(DP_,26);
DYNX(W_,135) = DYNX(DP_,33);
DYNX(W_,136) = DYNX(DP_,34);
DYNX(W_,137) = DYNX(DP_,35);
DYNX(W_,139) = DYNX(W_,126);
DYNX(W_,140) = DYNX(W_,129);
DYNX(W_,141) = DYNX(W_,130);
DYNX(W_,148) = DYNX(W_,139);
DYNX(DYNhelp,6) = sqrtGuarded(DYNX(W_,140)*DYNX(W_,140)+DYNX(W_,141)*
  DYNX(W_,141),"mimo_transferfunction1.miso[3].transferFunction[1].a[1]*mimo_transferfunction1.miso[3].transferFunction[1].a[1]+mimo_transferfunction1.miso[3].transferFunction[1].a[2]*mimo_transferfunction1.miso[3].transferFunction[1].a[2]");
DYNX(W_,150) = IF DYNX(W_,141) > 1E-013*DYNX(DYNhelp,6) THEN DYNX(W_,141) ELSE 
  1.0;
DYNX(W_,152) = DYNX(W_,127);
DYNX(W_,153) = DYNX(W_,131);
DYNX(W_,154) = DYNX(W_,132);
DYNX(W_,161) = DYNX(W_,152);
DYNX(DYNhelp,7) = sqrtGuarded(DYNX(W_,153)*DYNX(W_,153)+DYNX(W_,154)*
  DYNX(W_,154),"mimo_transferfunction1.miso[3].transferFunction[2].a[1]*mimo_transferfunction1.miso[3].transferFunction[2].a[1]+mimo_transferfunction1.miso[3].transferFunction[2].a[2]*mimo_transferfunction1.miso[3].transferFunction[2].a[2]");
DYNX(W_,163) = IF DYNX(W_,154) > 1E-013*DYNX(DYNhelp,7) THEN DYNX(W_,154) ELSE 
  1.0;
DYNX(W_,165) = DYNX(W_,128);
DYNX(W_,166) = DYNX(W_,133);
DYNX(W_,167) = DYNX(W_,134);
DYNX(W_,174) = DYNX(W_,165);
DYNX(DYNhelp,8) = sqrtGuarded(DYNX(W_,166)*DYNX(W_,166)+DYNX(W_,167)*
  DYNX(W_,167),"mimo_transferfunction1.miso[3].transferFunction[3].a[1]*mimo_transferfunction1.miso[3].transferFunction[3].a[1]+mimo_transferfunction1.miso[3].transferFunction[3].a[2]*mimo_transferfunction1.miso[3].transferFunction[3].a[2]");
DYNX(W_,176) = IF DYNX(W_,167) > 1E-013*DYNX(DYNhelp,8) THEN DYNX(W_,167) ELSE 
  1.0;
DYNX(W_,181) = DYNX(W_,135);
DYNX(W_,182) = DYNX(W_,136);
DYNX(W_,183) = DYNX(W_,137);
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,25) = DYNX(DP_,36);
DYNX(W_,38) = DYNX(DP_,38);
DYNX(W_,51) = DYNX(DP_,40);
DYNX(W_,84) = DYNX(DP_,46);
DYNX(W_,97) = DYNX(DP_,48);
DYNX(W_,110) = DYNX(DP_,50);
DYNX(W_,143) = DYNX(DP_,56);
DYNX(W_,156) = DYNX(DP_,58);
DYNX(W_,169) = DYNX(DP_,60);
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(W_,20) = DYNX(DP_,37);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,9) = divmacro(1.0,"1.0",DYNX(W_,32),"mimo_transferfunction1.miso[1].transferFunction[1].a_end");
DYNX(X_,0) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,9)*DYNX(W_,30)," -mimo_transferfunction1.miso[1].transferFunction[1].bb[2]/mimo_transferfunction1.miso[1].transferFunction[1].a_end",
    -DYNX(W_,20)," -mimo_transferfunction1.miso[1].transferFunction[1].y", 
  DYNX(X_,0),"mimo_transferfunction1.miso[1].transferFunction[1].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,33) = DYNX(DP_,39);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,10) = divmacro(1.0,"1.0",DYNX(W_,45),"mimo_transferfunction1.miso[1].transferFunction[2].a_end");
DYNX(X_,1) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,10)*DYNX(W_,43)," -mimo_transferfunction1.miso[1].transferFunction[2].bb[2]/mimo_transferfunction1.miso[1].transferFunction[2].a_end",
    -DYNX(W_,33)," -mimo_transferfunction1.miso[1].transferFunction[2].y", 
  DYNX(X_,1),"mimo_transferfunction1.miso[1].transferFunction[2].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,46) = DYNX(DP_,41);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,11) = divmacro(1.0,"1.0",DYNX(W_,58),"mimo_transferfunction1.miso[1].transferFunction[3].a_end");
DYNX(X_,2) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,11)*DYNX(W_,56)," -mimo_transferfunction1.miso[1].transferFunction[3].bb[2]/mimo_transferfunction1.miso[1].transferFunction[3].a_end",
    -DYNX(W_,46)," -mimo_transferfunction1.miso[1].transferFunction[3].y", 
  DYNX(X_,2),"mimo_transferfunction1.miso[1].transferFunction[3].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,79) = DYNX(DP_,47);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,12) = divmacro(1.0,"1.0",DYNX(W_,91),"mimo_transferfunction1.miso[2].transferFunction[1].a_end");
DYNX(X_,3) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,12)*DYNX(W_,89)," -mimo_transferfunction1.miso[2].transferFunction[1].bb[2]/mimo_transferfunction1.miso[2].transferFunction[1].a_end",
    -DYNX(W_,79)," -mimo_transferfunction1.miso[2].transferFunction[1].y", 
  DYNX(X_,3),"mimo_transferfunction1.miso[2].transferFunction[1].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,92) = DYNX(DP_,49);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,13) = divmacro(1.0,"1.0",DYNX(W_,104),"mimo_transferfunction1.miso[2].transferFunction[2].a_end");
DYNX(X_,4) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,13)*DYNX(W_,102)," -mimo_transferfunction1.miso[2].transferFunction[2].bb[2]/mimo_transferfunction1.miso[2].transferFunction[2].a_end",
    -DYNX(W_,92)," -mimo_transferfunction1.miso[2].transferFunction[2].y", 
  DYNX(X_,4),"mimo_transferfunction1.miso[2].transferFunction[2].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,105) = DYNX(DP_,51);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,14) = divmacro(1.0,"1.0",DYNX(W_,117),"mimo_transferfunction1.miso[2].transferFunction[3].a_end");
DYNX(X_,5) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,14)*DYNX(W_,115)," -mimo_transferfunction1.miso[2].transferFunction[3].bb[2]/mimo_transferfunction1.miso[2].transferFunction[3].a_end",
    -DYNX(W_,105)," -mimo_transferfunction1.miso[2].transferFunction[3].y", 
  DYNX(X_,5),"mimo_transferfunction1.miso[2].transferFunction[3].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,138) = DYNX(DP_,57);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,15) = divmacro(1.0,"1.0",DYNX(W_,150),"mimo_transferfunction1.miso[3].transferFunction[1].a_end");
DYNX(X_,6) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,15)*DYNX(W_,148)," -mimo_transferfunction1.miso[3].transferFunction[1].bb[2]/mimo_transferfunction1.miso[3].transferFunction[1].a_end",
    -DYNX(W_,138)," -mimo_transferfunction1.miso[3].transferFunction[1].y", 
  DYNX(X_,6),"mimo_transferfunction1.miso[3].transferFunction[1].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,151) = DYNX(DP_,59);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,16) = divmacro(1.0,"1.0",DYNX(W_,163),"mimo_transferfunction1.miso[3].transferFunction[2].a_end");
DYNX(X_,7) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,16)*DYNX(W_,161)," -mimo_transferfunction1.miso[3].transferFunction[2].bb[2]/mimo_transferfunction1.miso[3].transferFunction[2].a_end",
    -DYNX(W_,151)," -mimo_transferfunction1.miso[3].transferFunction[2].y", 
  DYNX(X_,7),"mimo_transferfunction1.miso[3].transferFunction[2].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,164) = DYNX(DP_,61);
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,17) = divmacro(1.0,"1.0",DYNX(W_,176),"mimo_transferfunction1.miso[3].transferFunction[3].a_end");
DYNX(X_,8) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,17)*DYNX(W_,174)," -mimo_transferfunction1.miso[3].transferFunction[3].bb[2]/mimo_transferfunction1.miso[3].transferFunction[3].a_end",
    -DYNX(W_,164)," -mimo_transferfunction1.miso[3].transferFunction[3].y", 
  DYNX(X_,8),"mimo_transferfunction1.miso[3].transferFunction[3].x_scaled[1]");
 /* End of Equation Block */ 

InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,1) = DYNX(DP_,67)+(IF LessTime(DYNX(DP_,68), 0) THEN 0 ELSE DYNX(DP_,66));
DYNX(F_,0) = divmacro(DYNX(W_,32)*DYNX(W_,1)-DYNX(W_,23)*DYNX(X_,0),
  "mimo_transferfunction1.miso[1].transferFunction[1].a_end*mimo_transferfunction1.u[1]-mimo_transferfunction1.miso[1].transferFunction[1].a[2]*mimo_transferfunction1.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,22),"mimo_transferfunction1.miso[1].transferFunction[1].a[1]");
DYNX(W_,2) = DYNX(DP_,70)+(IF LessTime(DYNX(DP_,71), 1) THEN 0 ELSE DYNX(DP_,69));
DYNX(F_,1) = divmacro(DYNX(W_,45)*DYNX(W_,2)-DYNX(W_,36)*DYNX(X_,1),
  "mimo_transferfunction1.miso[1].transferFunction[2].a_end*mimo_transferfunction1.u[2]-mimo_transferfunction1.miso[1].transferFunction[2].a[2]*mimo_transferfunction1.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,35),"mimo_transferfunction1.miso[1].transferFunction[2].a[1]");
DYNX(W_,3) = DYNX(DP_,73)+(IF LessTime(DYNX(DP_,74), 2) THEN 0 ELSE DYNX(DP_,72));
DYNX(F_,2) = divmacro(DYNX(W_,58)*DYNX(W_,3)-DYNX(W_,49)*DYNX(X_,2),
  "mimo_transferfunction1.miso[1].transferFunction[3].a_end*mimo_transferfunction1.u[3]-mimo_transferfunction1.miso[1].transferFunction[3].a[2]*mimo_transferfunction1.miso[1].transferFunction[3].x_scaled[1]",
  DYNX(W_,48),"mimo_transferfunction1.miso[1].transferFunction[3].a[1]");
DYNX(F_,3) = divmacro(DYNX(W_,91)*DYNX(W_,1)-DYNX(W_,82)*DYNX(X_,3),
  "mimo_transferfunction1.miso[2].transferFunction[1].a_end*mimo_transferfunction1.u[1]-mimo_transferfunction1.miso[2].transferFunction[1].a[2]*mimo_transferfunction1.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,81),"mimo_transferfunction1.miso[2].transferFunction[1].a[1]");
DYNX(F_,4) = divmacro(DYNX(W_,104)*DYNX(W_,2)-DYNX(W_,95)*DYNX(X_,4),
  "mimo_transferfunction1.miso[2].transferFunction[2].a_end*mimo_transferfunction1.u[2]-mimo_transferfunction1.miso[2].transferFunction[2].a[2]*mimo_transferfunction1.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,94),"mimo_transferfunction1.miso[2].transferFunction[2].a[1]");
DYNX(F_,5) = divmacro(DYNX(W_,117)*DYNX(W_,3)-DYNX(W_,108)*DYNX(X_,5),
  "mimo_transferfunction1.miso[2].transferFunction[3].a_end*mimo_transferfunction1.u[3]-mimo_transferfunction1.miso[2].transferFunction[3].a[2]*mimo_transferfunction1.miso[2].transferFunction[3].x_scaled[1]",
  DYNX(W_,107),"mimo_transferfunction1.miso[2].transferFunction[3].a[1]");
DYNX(F_,6) = divmacro(DYNX(W_,150)*DYNX(W_,1)-DYNX(W_,141)*DYNX(X_,6),
  "mimo_transferfunction1.miso[3].transferFunction[1].a_end*mimo_transferfunction1.u[1]-mimo_transferfunction1.miso[3].transferFunction[1].a[2]*mimo_transferfunction1.miso[3].transferFunction[1].x_scaled[1]",
  DYNX(W_,140),"mimo_transferfunction1.miso[3].transferFunction[1].a[1]");
DYNX(F_,7) = divmacro(DYNX(W_,163)*DYNX(W_,2)-DYNX(W_,154)*DYNX(X_,7),
  "mimo_transferfunction1.miso[3].transferFunction[2].a_end*mimo_transferfunction1.u[2]-mimo_transferfunction1.miso[3].transferFunction[2].a[2]*mimo_transferfunction1.miso[3].transferFunction[2].x_scaled[1]",
  DYNX(W_,153),"mimo_transferfunction1.miso[3].transferFunction[2].a[1]");
DYNX(F_,8) = divmacro(DYNX(W_,176)*DYNX(W_,3)-DYNX(W_,167)*DYNX(X_,8),
  "mimo_transferfunction1.miso[3].transferFunction[3].a_end*mimo_transferfunction1.u[3]-mimo_transferfunction1.miso[3].transferFunction[3].a[2]*mimo_transferfunction1.miso[3].transferFunction[3].x_scaled[1]",
  DYNX(W_,166),"mimo_transferfunction1.miso[3].transferFunction[3].a[1]");

AcceptedSection1

AcceptedSection2
DYNX(W_,20) = divmacro(DYNX(W_,30)*DYNX(X_,0),"mimo_transferfunction1.miso[1].transferFunction[1].bb[2]*mimo_transferfunction1.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,32),"mimo_transferfunction1.miso[1].transferFunction[1].a_end");
DYNX(W_,60) = delay(DYNX(W_,20), DYNX(W_,63), DYNX(W_,63), 0, "delay(mimo_transferfunction1.miso[1].transferFunction[1].y, mimo_transferfunction1.miso[1].fixedDelay[1].delayTime)");
DYNX(W_,33) = divmacro(DYNX(W_,43)*DYNX(X_,1),"mimo_transferfunction1.miso[1].transferFunction[2].bb[2]*mimo_transferfunction1.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,45),"mimo_transferfunction1.miso[1].transferFunction[2].a_end");
DYNX(W_,61) = delay(DYNX(W_,33), DYNX(W_,64), DYNX(W_,64), 1, "delay(mimo_transferfunction1.miso[1].transferFunction[2].y, mimo_transferfunction1.miso[1].fixedDelay[2].delayTime)");
DYNX(W_,46) = divmacro(DYNX(W_,56)*DYNX(X_,2),"mimo_transferfunction1.miso[1].transferFunction[3].bb[2]*mimo_transferfunction1.miso[1].transferFunction[3].x_scaled[1]",
  DYNX(W_,58),"mimo_transferfunction1.miso[1].transferFunction[3].a_end");
DYNX(W_,62) = delay(DYNX(W_,46), DYNX(W_,65), DYNX(W_,65), 2, "delay(mimo_transferfunction1.miso[1].transferFunction[3].y, mimo_transferfunction1.miso[1].fixedDelay[3].delayTime)");
DYNX(W_,4) = DYNX(DP_,43)*DYNX(W_,60)+DYNX(DP_,44)*DYNX(W_,61)+DYNX(DP_,45)*
  DYNX(W_,62);
DYNX(W_,79) = divmacro(DYNX(W_,89)*DYNX(X_,3),"mimo_transferfunction1.miso[2].transferFunction[1].bb[2]*mimo_transferfunction1.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,91),"mimo_transferfunction1.miso[2].transferFunction[1].a_end");
DYNX(W_,119) = delay(DYNX(W_,79), DYNX(W_,122), DYNX(W_,122), 3, 
  "delay(mimo_transferfunction1.miso[2].transferFunction[1].y, mimo_transferfunction1.miso[2].fixedDelay[1].delayTime)");
DYNX(W_,92) = divmacro(DYNX(W_,102)*DYNX(X_,4),"mimo_transferfunction1.miso[2].transferFunction[2].bb[2]*mimo_transferfunction1.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,104),"mimo_transferfunction1.miso[2].transferFunction[2].a_end");
DYNX(W_,120) = delay(DYNX(W_,92), DYNX(W_,123), DYNX(W_,123), 4, 
  "delay(mimo_transferfunction1.miso[2].transferFunction[2].y, mimo_transferfunction1.miso[2].fixedDelay[2].delayTime)");
DYNX(W_,105) = divmacro(DYNX(W_,115)*DYNX(X_,5),"mimo_transferfunction1.miso[2].transferFunction[3].bb[2]*mimo_transferfunction1.miso[2].transferFunction[3].x_scaled[1]",
  DYNX(W_,117),"mimo_transferfunction1.miso[2].transferFunction[3].a_end");
DYNX(W_,121) = delay(DYNX(W_,105), DYNX(W_,124), DYNX(W_,124), 5, 
  "delay(mimo_transferfunction1.miso[2].transferFunction[3].y, mimo_transferfunction1.miso[2].fixedDelay[3].delayTime)");
DYNX(W_,5) = DYNX(DP_,53)*DYNX(W_,119)+DYNX(DP_,54)*DYNX(W_,120)+DYNX(DP_,55)*
  DYNX(W_,121);
DYNX(W_,138) = divmacro(DYNX(W_,148)*DYNX(X_,6),"mimo_transferfunction1.miso[3].transferFunction[1].bb[2]*mimo_transferfunction1.miso[3].transferFunction[1].x_scaled[1]",
  DYNX(W_,150),"mimo_transferfunction1.miso[3].transferFunction[1].a_end");
DYNX(W_,178) = delay(DYNX(W_,138), DYNX(W_,181), DYNX(W_,181), 6, 
  "delay(mimo_transferfunction1.miso[3].transferFunction[1].y, mimo_transferfunction1.miso[3].fixedDelay[1].delayTime)");
DYNX(W_,151) = divmacro(DYNX(W_,161)*DYNX(X_,7),"mimo_transferfunction1.miso[3].transferFunction[2].bb[2]*mimo_transferfunction1.miso[3].transferFunction[2].x_scaled[1]",
  DYNX(W_,163),"mimo_transferfunction1.miso[3].transferFunction[2].a_end");
DYNX(W_,179) = delay(DYNX(W_,151), DYNX(W_,182), DYNX(W_,182), 7, 
  "delay(mimo_transferfunction1.miso[3].transferFunction[2].y, mimo_transferfunction1.miso[3].fixedDelay[2].delayTime)");
DYNX(W_,164) = divmacro(DYNX(W_,174)*DYNX(X_,8),"mimo_transferfunction1.miso[3].transferFunction[3].bb[2]*mimo_transferfunction1.miso[3].transferFunction[3].x_scaled[1]",
  DYNX(W_,176),"mimo_transferfunction1.miso[3].transferFunction[3].a_end");
DYNX(W_,180) = delay(DYNX(W_,164), DYNX(W_,183), DYNX(W_,183), 8, 
  "delay(mimo_transferfunction1.miso[3].transferFunction[3].y, mimo_transferfunction1.miso[3].fixedDelay[3].delayTime)");
DYNX(W_,6) = DYNX(DP_,63)*DYNX(W_,178)+DYNX(DP_,64)*DYNX(W_,179)+DYNX(DP_,65)*
  DYNX(W_,180);
DYNX(W_,25) = divmacro(DYNX(X_,0),"mimo_transferfunction1.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,32),"mimo_transferfunction1.miso[1].transferFunction[1].a_end");
DYNX(W_,38) = divmacro(DYNX(X_,1),"mimo_transferfunction1.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,45),"mimo_transferfunction1.miso[1].transferFunction[2].a_end");
DYNX(W_,51) = divmacro(DYNX(X_,2),"mimo_transferfunction1.miso[1].transferFunction[3].x_scaled[1]",
  DYNX(W_,58),"mimo_transferfunction1.miso[1].transferFunction[3].a_end");
DYNX(W_,84) = divmacro(DYNX(X_,3),"mimo_transferfunction1.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,91),"mimo_transferfunction1.miso[2].transferFunction[1].a_end");
DYNX(W_,97) = divmacro(DYNX(X_,4),"mimo_transferfunction1.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,104),"mimo_transferfunction1.miso[2].transferFunction[2].a_end");
DYNX(W_,110) = divmacro(DYNX(X_,5),"mimo_transferfunction1.miso[2].transferFunction[3].x_scaled[1]",
  DYNX(W_,117),"mimo_transferfunction1.miso[2].transferFunction[3].a_end");
DYNX(W_,143) = divmacro(DYNX(X_,6),"mimo_transferfunction1.miso[3].transferFunction[1].x_scaled[1]",
  DYNX(W_,150),"mimo_transferfunction1.miso[3].transferFunction[1].a_end");
DYNX(W_,156) = divmacro(DYNX(X_,7),"mimo_transferfunction1.miso[3].transferFunction[2].x_scaled[1]",
  DYNX(W_,163),"mimo_transferfunction1.miso[3].transferFunction[2].a_end");
DYNX(W_,169) = divmacro(DYNX(X_,8),"mimo_transferfunction1.miso[3].transferFunction[3].x_scaled[1]",
  DYNX(W_,176),"mimo_transferfunction1.miso[3].transferFunction[3].a_end");

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("mimo_transferfunction1.n", "Number of inputs (= number of outputs) [:#(type=Integer)]",\
 3, 0.0,0.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.num[1, 1, 1]", "Numerator of the system",\
 0, 3, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[1, 2, 1]", "Numerator of the system",\
 1, 1E-010, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[1, 3, 1]", "Numerator of the system",\
 2, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[2, 1, 1]", "Numerator of the system",\
 3, 4, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[2, 2, 1]", "Numerator of the system",\
 4, 7, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[2, 3, 1]", "Numerator of the system",\
 5, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[3, 1, 1]", "Numerator of the system",\
 6, 2, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[3, 2, 1]", "Numerator of the system",\
 7, 5, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.num[3, 3, 1]", "Numerator of the system",\
 8, 1E-010, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[1, 1, 1]", "Denominator of the system",\
 9, 10, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[1, 1, 2]", "Denominator of the system",\
 10, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[1, 2, 1]", "Denominator of the system",\
 11, 0.001, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[1, 2, 2]", "Denominator of the system",\
 12, 1.0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[1, 3, 1]", "Denominator of the system",\
 13, 5, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[1, 3, 2]", "Denominator of the system",\
 14, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[2, 1, 1]", "Denominator of the system",\
 15, 4, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[2, 1, 2]", "Denominator of the system",\
 16, 6, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[2, 2, 1]", "Denominator of the system",\
 17, 7, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[2, 2, 2]", "Denominator of the system",\
 18, 2, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[2, 3, 1]", "Denominator of the system",\
 19, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[2, 3, 2]", "Denominator of the system",\
 20, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[3, 1, 1]", "Denominator of the system",\
 21, 2, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[3, 1, 2]", "Denominator of the system",\
 22, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[3, 2, 1]", "Denominator of the system",\
 23, 50, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[3, 2, 2]", "Denominator of the system",\
 24, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[3, 3, 1]", "Denominator of the system",\
 25, 0.001, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.den[3, 3, 2]", "Denominator of the system",\
 26, 1.0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[1, 1]", "Delay for the system", 27,\
 10, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[1, 2]", "Delay for the system", 28,\
 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[1, 3]", "Delay for the system", 29,\
 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[2, 1]", "Delay for the system", 30,\
 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[2, 2]", "Delay for the system", 31,\
 23, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[2, 3]", "Delay for the system", 32,\
 1, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[3, 1]", "Delay for the system", 33,\
 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[3, 2]", "Delay for the system", 34,\
 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.delay[3, 3]", "Delay for the system", 35,\
 5, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.u[1]", "Connector of Real input signals",\
 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("mimo_transferfunction1.u[2]", "Connector of Real input signals",\
 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("mimo_transferfunction1.u[3]", "Connector of Real input signals",\
 0.0, 0.0,0.0,0.0,0,640)
DeclareVariable("mimo_transferfunction1.y[1]", "Connector of Real output signals",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.y[2]", "Connector of Real output signals",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.y[3]", "Connector of Real output signals",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[1].n", "Number of inputs [:#(type=Integer)]",\
 3, 0.0,0.0,0.0,0,517)
DeclareVariable("mimo_transferfunction1.miso[1].num[1, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].num[2, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].num[3, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].den[1, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].den[1, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].den[2, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].den[2, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].den[3, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].den[3, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].delay[1]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].delay[2]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].delay[3]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[1].u[1]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[1]", 1, 5, 1, 0)
DeclareAlias2("mimo_transferfunction1.miso[1].u[2]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[2]", 1, 5, 2, 0)
DeclareAlias2("mimo_transferfunction1.miso[1].u[3]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[3]", 1, 5, 3, 0)
DeclareAlias2("mimo_transferfunction1.miso[1].y", "Connector of Real output signal",\
 "mimo_transferfunction1.y[1]", 1, 5, 4, 0)
DeclareAlias2("mimo_transferfunction1.miso[1].transferFunction[1].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[1]", 1, 5, 1, 0)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[1].transferFunction[1].x_start[1]",\
 "Initial or guess values of states", 36, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[1].transferFunction[1].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 37,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[1].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[1].transferFunction[1].x_scaled[1]", \
"Scaled vector x", 0, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[1].transferFunction[1].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("mimo_transferfunction1.miso[1].transferFunction[2].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[2]", 1, 5, 2, 0)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[1].transferFunction[2].x_start[1]",\
 "Initial or guess values of states", 38, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[1].transferFunction[2].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 39,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[2].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[1].transferFunction[2].x_scaled[1]", \
"Scaled vector x", 1, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[1].transferFunction[2].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("mimo_transferfunction1.miso[1].transferFunction[3].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[3]", 1, 5, 3, 0)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[1].transferFunction[3].x_start[1]",\
 "Initial or guess values of states", 40, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[1].transferFunction[3].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 41,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[1].transferFunction[3].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[1].transferFunction[3].x_scaled[1]", \
"Scaled vector x", 2, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[1].transferFunction[3].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("mimo_transferfunction1.miso[1].add.significantDigits", \
"Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 42, 5, 1.0,1E+100,0.0,0,564)
DeclareVariable("mimo_transferfunction1.miso[1].add.nu", "Number of input connections [:#(type=Integer)]",\
 3, 0.0,1E+100,0.0,0,1541)
DeclareVariable("mimo_transferfunction1.miso[1].add.u[1]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("mimo_transferfunction1.miso[1].add.u[2]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("mimo_transferfunction1.miso[1].add.u[3]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareAlias2("mimo_transferfunction1.miso[1].add.y", "", "mimo_transferfunction1.y[1]", 1,\
 5, 4, 0)
DeclareParameter("mimo_transferfunction1.miso[1].add.k[1]", "Input gains", 43, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[1].add.k[2]", "Input gains", 44, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[1].add.k[3]", "Input gains", 45, 1,\
 0.0,0.0,0.0,0,560)
DeclareAlias2("mimo_transferfunction1.miso[1].fixedDelay[1].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[1].transferFunction[1].y", 1, 5, 20, 0)
DeclareAlias2("mimo_transferfunction1.miso[1].fixedDelay[1].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[1].add.u[1]", 1, 5, 60, 0)
DeclareVariable("mimo_transferfunction1.miso[1].fixedDelay[1].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[1].fixedDelay[2].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[1].transferFunction[2].y", 1, 5, 33, 0)
DeclareAlias2("mimo_transferfunction1.miso[1].fixedDelay[2].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[1].add.u[2]", 1, 5, 61, 0)
DeclareVariable("mimo_transferfunction1.miso[1].fixedDelay[2].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[1].fixedDelay[3].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[1].transferFunction[3].y", 1, 5, 46, 0)
DeclareAlias2("mimo_transferfunction1.miso[1].fixedDelay[3].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[1].add.u[3]", 1, 5, 62, 0)
DeclareVariable("mimo_transferfunction1.miso[1].fixedDelay[3].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].n", "Number of inputs [:#(type=Integer)]",\
 3, 0.0,0.0,0.0,0,517)
DeclareVariable("mimo_transferfunction1.miso[2].num[1, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].num[2, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].num[3, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].den[1, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].den[1, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].den[2, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].den[2, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].den[3, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].den[3, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].delay[1]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].delay[2]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].delay[3]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[2].u[1]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[1]", 1, 5, 1, 0)
DeclareAlias2("mimo_transferfunction1.miso[2].u[2]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[2]", 1, 5, 2, 0)
DeclareAlias2("mimo_transferfunction1.miso[2].u[3]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[3]", 1, 5, 3, 0)
DeclareAlias2("mimo_transferfunction1.miso[2].y", "Connector of Real output signal",\
 "mimo_transferfunction1.y[2]", 1, 5, 5, 0)
DeclareAlias2("mimo_transferfunction1.miso[2].transferFunction[1].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[1]", 1, 5, 1, 0)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[2].transferFunction[1].x_start[1]",\
 "Initial or guess values of states", 46, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[2].transferFunction[1].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 47,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[1].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[2].transferFunction[1].x_scaled[1]", \
"Scaled vector x", 3, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[2].transferFunction[1].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("mimo_transferfunction1.miso[2].transferFunction[2].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[2]", 1, 5, 2, 0)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[2].transferFunction[2].x_start[1]",\
 "Initial or guess values of states", 48, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[2].transferFunction[2].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 49,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[2].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[2].transferFunction[2].x_scaled[1]", \
"Scaled vector x", 4, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[2].transferFunction[2].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("mimo_transferfunction1.miso[2].transferFunction[3].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[3]", 1, 5, 3, 0)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[2].transferFunction[3].x_start[1]",\
 "Initial or guess values of states", 50, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[2].transferFunction[3].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 51,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[2].transferFunction[3].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[2].transferFunction[3].x_scaled[1]", \
"Scaled vector x", 5, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[2].transferFunction[3].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("mimo_transferfunction1.miso[2].add.significantDigits", \
"Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 52, 5, 1.0,1E+100,0.0,0,564)
DeclareVariable("mimo_transferfunction1.miso[2].add.nu", "Number of input connections [:#(type=Integer)]",\
 3, 0.0,1E+100,0.0,0,1541)
DeclareVariable("mimo_transferfunction1.miso[2].add.u[1]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("mimo_transferfunction1.miso[2].add.u[2]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("mimo_transferfunction1.miso[2].add.u[3]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareAlias2("mimo_transferfunction1.miso[2].add.y", "", "mimo_transferfunction1.y[2]", 1,\
 5, 5, 0)
DeclareParameter("mimo_transferfunction1.miso[2].add.k[1]", "Input gains", 53, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[2].add.k[2]", "Input gains", 54, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[2].add.k[3]", "Input gains", 55, 1,\
 0.0,0.0,0.0,0,560)
DeclareAlias2("mimo_transferfunction1.miso[2].fixedDelay[1].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[2].transferFunction[1].y", 1, 5, 79, 0)
DeclareAlias2("mimo_transferfunction1.miso[2].fixedDelay[1].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[2].add.u[1]", 1, 5, 119, 0)
DeclareVariable("mimo_transferfunction1.miso[2].fixedDelay[1].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[2].fixedDelay[2].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[2].transferFunction[2].y", 1, 5, 92, 0)
DeclareAlias2("mimo_transferfunction1.miso[2].fixedDelay[2].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[2].add.u[2]", 1, 5, 120, 0)
DeclareVariable("mimo_transferfunction1.miso[2].fixedDelay[2].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[2].fixedDelay[3].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[2].transferFunction[3].y", 1, 5, 105, 0)
DeclareAlias2("mimo_transferfunction1.miso[2].fixedDelay[3].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[2].add.u[3]", 1, 5, 121, 0)
DeclareVariable("mimo_transferfunction1.miso[2].fixedDelay[3].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].n", "Number of inputs [:#(type=Integer)]",\
 3, 0.0,0.0,0.0,0,517)
DeclareVariable("mimo_transferfunction1.miso[3].num[1, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].num[2, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].num[3, 1]", "Numerator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].den[1, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].den[1, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].den[2, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].den[2, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].den[3, 1]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].den[3, 2]", "Denominator of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].delay[1]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].delay[2]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].delay[3]", " Delay of the system",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[3].u[1]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[1]", 1, 5, 1, 0)
DeclareAlias2("mimo_transferfunction1.miso[3].u[2]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[2]", 1, 5, 2, 0)
DeclareAlias2("mimo_transferfunction1.miso[3].u[3]", "Connector of Real input signals",\
 "mimo_transferfunction1.u[3]", 1, 5, 3, 0)
DeclareAlias2("mimo_transferfunction1.miso[3].y", "Connector of Real output signal",\
 "mimo_transferfunction1.y[3]", 1, 5, 6, 0)
DeclareAlias2("mimo_transferfunction1.miso[3].transferFunction[1].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[1]", 1, 5, 1, 0)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[3].transferFunction[1].x_start[1]",\
 "Initial or guess values of states", 56, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[3].transferFunction[1].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 57,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[1].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[3].transferFunction[1].x_scaled[1]", \
"Scaled vector x", 6, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[3].transferFunction[1].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("mimo_transferfunction1.miso[3].transferFunction[2].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[2]", 1, 5, 2, 0)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[3].transferFunction[2].x_start[1]",\
 "Initial or guess values of states", 58, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[3].transferFunction[2].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 59,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[2].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[3].transferFunction[2].x_scaled[1]", \
"Scaled vector x", 7, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[3].transferFunction[2].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("mimo_transferfunction1.miso[3].transferFunction[3].u", \
"Connector of Real input signal", "mimo_transferfunction1.u[3]", 1, 5, 3, 0)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].y", \
"Connector of Real output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].b[1]", \
"Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].a[1]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].a[2]", \
"Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].initType", \
"Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("mimo_transferfunction1.miso[3].transferFunction[3].x_start[1]",\
 "Initial or guess values of states", 60, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[3].transferFunction[3].y_start", \
"Initial value of output (derivatives of y are zero up to nx-1-th derivative)", 61,\
 0, 0.0,0.0,0.0,0,560)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].x[1]", \
"State of transfer function from controller canonical form", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].na", \
"Size of Denominator of transfer function. [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].nb", \
"Size of Numerator of transfer function. [:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].nx", \
"[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].bb[1]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].bb[2]", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].d", "", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("mimo_transferfunction1.miso[3].transferFunction[3].a_end", "", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareState("mimo_transferfunction1.miso[3].transferFunction[3].x_scaled[1]", \
"Scaled vector x", 8, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("mimo_transferfunction1.miso[3].transferFunction[3].der(x_scaled[1])",\
 "der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("mimo_transferfunction1.miso[3].add.significantDigits", \
"Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 62, 5, 1.0,1E+100,0.0,0,564)
DeclareVariable("mimo_transferfunction1.miso[3].add.nu", "Number of input connections [:#(type=Integer)]",\
 3, 0.0,1E+100,0.0,0,1541)
DeclareVariable("mimo_transferfunction1.miso[3].add.u[1]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("mimo_transferfunction1.miso[3].add.u[2]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("mimo_transferfunction1.miso[3].add.u[3]", "", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareAlias2("mimo_transferfunction1.miso[3].add.y", "", "mimo_transferfunction1.y[3]", 1,\
 5, 6, 0)
DeclareParameter("mimo_transferfunction1.miso[3].add.k[1]", "Input gains", 63, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[3].add.k[2]", "Input gains", 64, 1,\
 0.0,0.0,0.0,0,560)
DeclareParameter("mimo_transferfunction1.miso[3].add.k[3]", "Input gains", 65, 1,\
 0.0,0.0,0.0,0,560)
DeclareAlias2("mimo_transferfunction1.miso[3].fixedDelay[1].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[3].transferFunction[1].y", 1, 5, 138, 0)
DeclareAlias2("mimo_transferfunction1.miso[3].fixedDelay[1].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[3].add.u[1]", 1, 5, 178, 0)
DeclareVariable("mimo_transferfunction1.miso[3].fixedDelay[1].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[3].fixedDelay[2].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[3].transferFunction[2].y", 1, 5, 151, 0)
DeclareAlias2("mimo_transferfunction1.miso[3].fixedDelay[2].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[3].add.u[2]", 1, 5, 179, 0)
DeclareVariable("mimo_transferfunction1.miso[3].fixedDelay[2].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("mimo_transferfunction1.miso[3].fixedDelay[3].u", "Connector of Real input signal",\
 "mimo_transferfunction1.miso[3].transferFunction[3].y", 1, 5, 164, 0)
DeclareAlias2("mimo_transferfunction1.miso[3].fixedDelay[3].y", "Connector of Real output signal",\
 "mimo_transferfunction1.miso[3].add.u[3]", 1, 5, 180, 0)
DeclareVariable("mimo_transferfunction1.miso[3].fixedDelay[3].delayTime", \
"Delay time of output with respect to input signal [s]", 1, 0.0,0.0,0.0,0,513)
DeclareParameter("step.height", "Height of step", 66, -2, 0.0,0.0,0.0,0,560)
DeclareAlias2("step.y", "Connector of Real output signal", "mimo_transferfunction1.u[1]", 1,\
 5, 1, 0)
DeclareParameter("step.offset", "Offset of output signal y", 67, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("step.startTime", "Output y = offset for time < startTime [s]",\
 68, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("step1.height", "Height of step", 69, 3, 0.0,0.0,0.0,0,560)
DeclareAlias2("step1.y", "Connector of Real output signal", "mimo_transferfunction1.u[2]", 1,\
 5, 2, 0)
DeclareParameter("step1.offset", "Offset of output signal y", 70, 0, 0.0,0.0,0.0,\
0,560)
DeclareParameter("step1.startTime", "Output y = offset for time < startTime [s]",\
 71, 5, 0.0,0.0,0.0,0,560)
DeclareParameter("step2.height", "Height of step", 72, -5, 0.0,0.0,0.0,0,560)
DeclareAlias2("step2.y", "Connector of Real output signal", "mimo_transferfunction1.u[3]", 1,\
 5, 3, 0)
DeclareParameter("step2.offset", "Offset of output signal y", 73, 0, 0.0,0.0,0.0,\
0,560)
DeclareParameter("step2.startTime", "Output y = offset for time < startTime [s]",\
 74, 10, 0.0,0.0,0.0,0,560)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
