/* DSblock model generated by Dymola from Modelica model Masterthesis.Models.mimo_closedloop
 Dymola Version 2017 FD01 (64-bit), 2016-10-11 translated this at Fri Sep 01 15:51:42 2017

   */
#ifndef DYN_MULTINSTANCE
#define DYN_MULTINSTANCE 1
#endif

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

BreakSectionFunctionDef(1)
BreakSectionFunctionDef(0)
#define NX_    8
#define NX2_   0
#define NU_    2
#define NY_    2
#define NW_    221
#define NP_    72
#define NPS_   0
#define MAXAuxStr_   12
#define MAXAuxStrLen_   500
#define NHash1_ -1042612433
#define NHash2_ 194974550
#define NHash3_ 0
#define NI_    0
#define NRelF_ 8
#define NRel_  8
#define NTim_  4
#define NSamp_ 0
#define NCons_ 0
#define NA_    98
#define SizePre_ 4
#define SizeEq_ 0
#define SizeDelay_ 8
#define QNLmax_ 0
#define MAXAux 8
#define NrDymolaTimers_ 0
#define NWhen_ 8
#define NCheckIf_ 0
#define NGlobalHelp_ 12
#define NGlobalHelpI_ 4
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#define DYNCALLFMUREINIT
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Masterthesis.Models.mimo_closedloop";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/juliu/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
DYMOLA_STATIC const char*GUIDString="{5da9429b-325c-42ea-9d80-c70862405f1f}";
DYMOLA_STATIC const double cvodeTolerance=1E-005;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 2;
DYNX(W_,1) = 2;
DYNX(W_,2) = 2;
DYNX(W_,21) = 2;
DYNX(W_,36) = 2;
DYNX(W_,37) = 1;
DYNX(W_,38) = 1;
DYNX(W_,49) = 2;
DYNX(W_,50) = 1;
DYNX(W_,51) = 1;
DYNX(W_,56) = 2;
DYNX(W_,61) = 2;
DYNX(W_,76) = 2;
DYNX(W_,77) = 1;
DYNX(W_,78) = 1;
DYNX(W_,89) = 2;
DYNX(W_,90) = 1;
DYNX(W_,91) = 1;
DYNX(W_,96) = 2;
DYNX(W_,101) = 2;
DYNX(W_,116) = 2;
DYNX(W_,123) = 2;
DYNX(W_,129) = false;
DYNX(W_,130) = false;
DYNX(W_,131) = false;
DYNX(W_,135) = false;
DYNX(W_,136) = false;
DYNX(W_,150) = false;
DYNX(W_,151) = false;
DYNX(W_,152) = false;
DYNX(W_,156) = false;
DYNX(W_,157) = false;
DYNX(W_,166) = 2;
DYNX(W_,173) = 2;
DYNX(W_,179) = false;
DYNX(W_,180) = false;
DYNX(W_,181) = false;
DYNX(W_,185) = false;
DYNX(W_,186) = false;
DYNX(W_,200) = false;
DYNX(W_,201) = false;
DYNX(W_,202) = false;
DYNX(W_,206) = false;
DYNX(W_,207) = false;
DYNX(W_,216) = 2;
DYNX(W_,34) = 4;
DYNX(W_,39) = 0.0;
DYNX(W_,41) = 0.0;
DYNX(W_,47) = 4;
DYNX(W_,52) = 0.0;
DYNX(W_,54) = 0.0;
DYNX(W_,74) = 4;
DYNX(W_,79) = 0.0;
DYNX(W_,81) = 0.0;
DYNX(W_,87) = 4;
DYNX(W_,92) = 0.0;
DYNX(W_,94) = 0.0;
#endif
DYNSetAuxString(did_, "PI", 0);
DYNSetAuxString(did_, "ki", 1);
DYNSetAuxString(did_, "initialOutput", 2);
DYNSetAuxString(did_, "PI", 3);
DYNSetAuxString(did_, "ki", 4);
DYNSetAuxString(did_, "initialOutput", 5);
DYNSetAuxString(did_, "PI", 6);
DYNSetAuxString(did_, "ki", 7);
DYNSetAuxString(did_, "initialOutput", 8);
DYNSetAuxString(did_, "PI", 9);
DYNSetAuxString(did_, "ki", 10);
DYNSetAuxString(did_, "initialOutput", 11);
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,126) = false;
DYNX(W_,133) = true;
DYNX(W_,147) = false;
DYNX(W_,154) = true;
DYNX(W_,176) = false;
DYNX(W_,183) = true;
DYNX(W_,197) = false;
DYNX(W_,204) = true;
#endif
BoundParameterSection
DYNX(W_,3) = DYNX(DP_,0);
DYNX(W_,4) = DYNX(DP_,1);
DYNX(W_,5) = DYNX(DP_,2);
DYNX(W_,6) = DYNX(DP_,3);
DYNX(W_,7) = DYNX(DP_,4);
DYNX(W_,8) = DYNX(DP_,5);
DYNX(W_,9) = DYNX(DP_,6);
DYNX(W_,10) = DYNX(DP_,7);
DYNX(W_,11) = DYNX(DP_,8);
DYNX(W_,12) = DYNX(DP_,9);
DYNX(W_,13) = DYNX(DP_,10);
DYNX(W_,14) = DYNX(DP_,11);
DYNX(W_,15) = DYNX(DP_,12);
DYNX(W_,16) = DYNX(DP_,13);
DYNX(W_,17) = DYNX(DP_,14);
DYNX(W_,18) = DYNX(DP_,15);
DYNX(W_,22) = DYNX(W_,3);
DYNX(W_,23) = DYNX(W_,4);
DYNX(W_,24) = DYNX(W_,7);
DYNX(W_,25) = DYNX(W_,8);
DYNX(W_,26) = DYNX(W_,9);
DYNX(W_,27) = DYNX(W_,10);
DYNX(W_,28) = DYNX(W_,15);
DYNX(W_,29) = DYNX(W_,16);
DYNX(W_,31) = DYNX(W_,22);
DYNX(W_,32) = DYNX(W_,24);
DYNX(W_,33) = DYNX(W_,25);
DYNX(W_,40) = DYNX(W_,31);
DYNX(DYNhelp,0) = sqrtGuarded(DYNX(W_,32)*DYNX(W_,32)+DYNX(W_,33)*DYNX(W_,33),
  "System.miso[1].transferFunction[1].a[1]*System.miso[1].transferFunction[1].a[1]+System.miso[1].transferFunction[1].a[2]*System.miso[1].transferFunction[1].a[2]");
DYNX(W_,42) = IF DYNX(W_,33) > 1E-013*DYNX(DYNhelp,0) THEN DYNX(W_,33) ELSE 1.0;
DYNX(W_,44) = DYNX(W_,23);
DYNX(W_,45) = DYNX(W_,26);
DYNX(W_,46) = DYNX(W_,27);
DYNX(W_,53) = DYNX(W_,44);
DYNX(DYNhelp,1) = sqrtGuarded(DYNX(W_,45)*DYNX(W_,45)+DYNX(W_,46)*DYNX(W_,46),
  "System.miso[1].transferFunction[2].a[1]*System.miso[1].transferFunction[2].a[1]+System.miso[1].transferFunction[2].a[2]*System.miso[1].transferFunction[2].a[2]");
DYNX(W_,55) = IF DYNX(W_,46) > 1E-013*DYNX(DYNhelp,1) THEN DYNX(W_,46) ELSE 1.0;
DYNX(W_,59) = DYNX(W_,28);
DYNX(W_,60) = DYNX(W_,29);
DYNX(W_,62) = DYNX(W_,5);
DYNX(W_,63) = DYNX(W_,6);
DYNX(W_,64) = DYNX(W_,11);
DYNX(W_,65) = DYNX(W_,12);
DYNX(W_,66) = DYNX(W_,13);
DYNX(W_,67) = DYNX(W_,14);
DYNX(W_,68) = DYNX(W_,17);
DYNX(W_,69) = DYNX(W_,18);
DYNX(W_,71) = DYNX(W_,62);
DYNX(W_,72) = DYNX(W_,64);
DYNX(W_,73) = DYNX(W_,65);
DYNX(W_,80) = DYNX(W_,71);
DYNX(DYNhelp,2) = sqrtGuarded(DYNX(W_,72)*DYNX(W_,72)+DYNX(W_,73)*DYNX(W_,73),
  "System.miso[2].transferFunction[1].a[1]*System.miso[2].transferFunction[1].a[1]+System.miso[2].transferFunction[1].a[2]*System.miso[2].transferFunction[1].a[2]");
DYNX(W_,82) = IF DYNX(W_,73) > 1E-013*DYNX(DYNhelp,2) THEN DYNX(W_,73) ELSE 1.0;
DYNX(W_,84) = DYNX(W_,63);
DYNX(W_,85) = DYNX(W_,66);
DYNX(W_,86) = DYNX(W_,67);
DYNX(W_,93) = DYNX(W_,84);
DYNX(DYNhelp,3) = sqrtGuarded(DYNX(W_,85)*DYNX(W_,85)+DYNX(W_,86)*DYNX(W_,86),
  "System.miso[2].transferFunction[2].a[1]*System.miso[2].transferFunction[2].a[1]+System.miso[2].transferFunction[2].a[2]*System.miso[2].transferFunction[2].a[2]");
DYNX(W_,95) = IF DYNX(W_,86) > 1E-013*DYNX(DYNhelp,3) THEN DYNX(W_,86) ELSE 1.0;
DYNX(W_,99) = DYNX(W_,68);
DYNX(W_,100) = DYNX(W_,69);
DYNX(W_,102) = DYNX(DP_,16);
DYNX(W_,103) = DYNX(DP_,17);
DYNX(W_,104) = DYNX(DP_,18);
DYNX(W_,105) = DYNX(DP_,19);
DYNX(W_,106) = DYNX(DP_,20);
DYNX(W_,107) = DYNX(DP_,21);
DYNX(W_,108) = DYNX(DP_,22);
DYNX(W_,109) = DYNX(DP_,23);
DYNX(W_,110) = DYNX(DP_,24);
DYNX(W_,111) = DYNX(DP_,25);
DYNX(W_,112) = DYNX(DP_,26);
DYNX(W_,113) = DYNX(DP_,27);
DYNX(W_,117) = DYNX(W_,102);
DYNX(W_,118) = DYNX(W_,103);
DYNX(W_,119) = DYNX(W_,106);
DYNX(W_,120) = DYNX(W_,107);
DYNX(W_,121) = DYNX(W_,110);
DYNX(W_,122) = DYNX(W_,111);
DYNX(W_,127) = DYNX(W_,117);
DYNX(W_,128) = DYNX(W_,119);
DYNX(W_,132) =  -DYNX(DP_,51);
DYNX(W_,134) = DYNX(W_,121);
DYNX(W_,142) = DYNX(W_,127);
DYNX(W_,143) = DYNX(W_,128);
DYNX(W_,144) = DYNX(DP_,50);
DYNX(W_,148) = DYNX(W_,118);
DYNX(W_,149) = DYNX(W_,120);
DYNX(W_,153) =  -DYNX(DP_,56);
DYNX(W_,155) = DYNX(W_,122);
DYNX(W_,163) = DYNX(W_,148);
DYNX(W_,164) = DYNX(W_,149);
DYNX(W_,165) = DYNX(DP_,55);
DYNX(W_,167) = DYNX(W_,104);
DYNX(W_,168) = DYNX(W_,105);
DYNX(W_,169) = DYNX(W_,108);
DYNX(W_,170) = DYNX(W_,109);
DYNX(W_,171) = DYNX(W_,112);
DYNX(W_,172) = DYNX(W_,113);
DYNX(W_,177) = DYNX(W_,167);
DYNX(W_,178) = DYNX(W_,169);
DYNX(W_,182) =  -DYNX(DP_,64);
DYNX(W_,184) = DYNX(W_,171);
DYNX(W_,192) = DYNX(W_,177);
DYNX(W_,193) = DYNX(W_,178);
DYNX(W_,194) = DYNX(DP_,63);
DYNX(W_,198) = DYNX(W_,168);
DYNX(W_,199) = DYNX(W_,170);
DYNX(W_,203) =  -DYNX(DP_,69);
DYNX(W_,205) = DYNX(W_,172);
DYNX(W_,213) = DYNX(W_,198);
DYNX(W_,214) = DYNX(W_,199);
DYNX(W_,215) = DYNX(DP_,68);
DYNX(W_,217) = DYNX(DP_,28);
DYNX(W_,218) = DYNX(DP_,29);
DYNX(W_,219) = DYNX(DP_,30);
DYNX(W_,220) = DYNX(DP_,31);
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(Y_,0) = 0;
DYNX(Y_,1) = 0;
#endif
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,35) = DYNX(DP_,32);
DYNX(W_,48) = DYNX(DP_,34);
DYNX(W_,75) = DYNX(DP_,39);
DYNX(W_,88) = DYNX(DP_,41);
DYNX(W_,124) = DYNX(DP_,52);
DYNX(W_,145) = DYNX(DP_,57);
DYNX(W_,174) = DYNX(DP_,65);
DYNX(W_,195) = DYNX(DP_,70);
InitialSection
DefaultSection
InitializeData(0)
InitialSection
DYNX(Aux_,0) = DYNX(W_,124);
DYNX(Aux_,1) = DYNX(W_,139);
DYNX(Aux_,2) = DYNX(W_,145);
DYNX(Aux_,3) = DYNX(W_,160);
DYNX(Aux_,4) = DYNX(W_,174);
DYNX(Aux_,5) = DYNX(W_,189);
DYNX(Aux_,6) = DYNX(W_,195);
DYNX(Aux_,7) = DYNX(W_,210);
InitialSection
InitialSection2
DYNX(W_,139) = DYNX(DP_,52);
DYNX(W_,160) = DYNX(DP_,57);
DYNX(W_,189) = DYNX(DP_,65);
DYNX(W_,210) = DYNX(DP_,70);
DYNX(W_,102) = DYNX(DP_,16);
DYNX(W_,117) = DYNX(W_,102);
DYNX(W_,127) = DYNX(W_,117);
DYNX(W_,142) = DYNX(W_,127);
DYNX(W_,110) = DYNX(DP_,24);
DYNX(W_,121) = DYNX(W_,110);
DYNX(W_,134) = DYNX(W_,121);
DYNX(W_,30) = DYNX(DP_,33);
DYNX(W_,15) = DYNX(DP_,12);
DYNX(W_,28) = DYNX(W_,15);
DYNX(W_,59) = DYNX(W_,28);
DYNX(W_,57) = delay(DYNX(W_,30), DYNX(W_,59), DYNX(W_,59), 0, "delay(System.miso[1].transferFunction[1].y, System.miso[1].fixedDelay[1].delayTime)");
DYNX(W_,43) = DYNX(DP_,35);
DYNX(W_,16) = DYNX(DP_,13);
DYNX(W_,29) = DYNX(W_,16);
DYNX(W_,60) = DYNX(W_,29);
DYNX(W_,58) = delay(DYNX(W_,43), DYNX(W_,60), DYNX(W_,60), 1, "delay(System.miso[1].transferFunction[2].y, System.miso[1].fixedDelay[2].delayTime)");
DYNX(Y_,0) = DYNX(DP_,37)*DYNX(W_,57)+DYNX(DP_,38)*DYNX(W_,58);
DYNX(W_,141) = DYNX(W_,134)*DYNX(U_,0)-DYNX(Y_,0);
DYNX(X_,4) = DYNX(DP_,52)-DYNX(W_,142)*DYNX(W_,141);
DYNX(W_,137) = GreaterEqualTime(DYNX(DP_,53), 0);
DYNX(W_,138) = DYNX(W_,142)*DYNX(W_,141)+DYNX(X_,4);
DYNX(W_,132) =  -DYNX(DP_,51);
AssertModelica(DYNX(DP_,51) >= DYNX(W_,132),"Decentral_Controller.pi[1].pIController_sw[1].yMax >= Decentral_Controller.pi[1].pIController_sw[1].yMin",
   StringAdd(StringAdd(StringAdd(StringAdd("PI controller output limits are not consistent: yMax (=",
  Real2String2(DYNX(DP_,51), true, 0)),") < yMin (="),Real2String2(DYNX(W_,132),
   true, 0)),")"));
PopAllMarks();
AssertModelica(DYNX(DP_,52) >= DYNX(W_,132) AND DYNX(DP_,52) <= DYNX(DP_,51),
  "Decentral_Controller.pi[1].pIController_sw[1].yInitial >= Decentral_Controller.pi[1].pIController_sw[1].yMin and Decentral_Controller.pi[1].pIController_sw[1].yInitial <= Decentral_Controller.pi[1].pIController_sw[1].yMax",
   "Output of PI controller yInitial must be between limits.");
DYNX(W_,124) = IF DYNX(W_,137) THEN (IF GreaterS(DYNX(W_,138),"Decentral_Controller.pi[1].pIController_sw[1].y_unlim",
   DYNX(DP_,51),"Decentral_Controller.pi[1].pIController_sw[1].yMax", 0) THEN 
  DYNX(DP_,51) ELSE IF LessS(DYNX(W_,138),"Decentral_Controller.pi[1].pIController_sw[1].y_unlim",
   DYNX(W_,132),"Decentral_Controller.pi[1].pIController_sw[1].yMin", 1) THEN 
  DYNX(W_,132) ELSE DYNX(W_,138)) ELSE DYNX(W_,139);
InitialSection
DYNX(Aux_,0) = DYNX(W_,124);
DYNX(Aux_,1) = DYNX(W_,139);
InitialSection2
DYNX(W_,103) = DYNX(DP_,17);
DYNX(W_,118) = DYNX(W_,103);
DYNX(W_,148) = DYNX(W_,118);
DYNX(W_,163) = DYNX(W_,148);
DYNX(W_,111) = DYNX(DP_,25);
DYNX(W_,122) = DYNX(W_,111);
DYNX(W_,155) = DYNX(W_,122);
DYNX(W_,70) = DYNX(DP_,40);
DYNX(W_,17) = DYNX(DP_,14);
DYNX(W_,68) = DYNX(W_,17);
DYNX(W_,99) = DYNX(W_,68);
DYNX(W_,97) = delay(DYNX(W_,70), DYNX(W_,99), DYNX(W_,99), 2, "delay(System.miso[2].transferFunction[1].y, System.miso[2].fixedDelay[1].delayTime)");
DYNX(W_,83) = DYNX(DP_,42);
DYNX(W_,18) = DYNX(DP_,15);
DYNX(W_,69) = DYNX(W_,18);
DYNX(W_,100) = DYNX(W_,69);
DYNX(W_,98) = delay(DYNX(W_,83), DYNX(W_,100), DYNX(W_,100), 3, "delay(System.miso[2].transferFunction[2].y, System.miso[2].fixedDelay[2].delayTime)");
DYNX(Y_,1) = DYNX(DP_,44)*DYNX(W_,97)+DYNX(DP_,45)*DYNX(W_,98);
DYNX(W_,162) = DYNX(W_,155)*DYNX(U_,1)-DYNX(Y_,1);
BreakSectionFunctionCallNew(0);
BreakSectionFunctionEnd()
BreakSectionFunctionStart(1);
DYNX(X_,5) = DYNX(DP_,57)-DYNX(W_,163)*DYNX(W_,162);
DYNX(W_,158) = GreaterEqualTime(DYNX(DP_,58), 1);
DYNX(W_,159) = DYNX(W_,163)*DYNX(W_,162)+DYNX(X_,5);
DYNX(W_,153) =  -DYNX(DP_,56);
AssertModelica(DYNX(DP_,56) >= DYNX(W_,153),"Decentral_Controller.pi[1].pIController_sw[2].yMax >= Decentral_Controller.pi[1].pIController_sw[2].yMin",
   StringAdd(StringAdd(StringAdd(StringAdd("PI controller output limits are not consistent: yMax (=",
  Real2String2(DYNX(DP_,56), true, 0)),") < yMin (="),Real2String2(DYNX(W_,153),
   true, 0)),")"));
PopAllMarks();
AssertModelica(DYNX(DP_,57) >= DYNX(W_,153) AND DYNX(DP_,57) <= DYNX(DP_,56),
  "Decentral_Controller.pi[1].pIController_sw[2].yInitial >= Decentral_Controller.pi[1].pIController_sw[2].yMin and Decentral_Controller.pi[1].pIController_sw[2].yInitial <= Decentral_Controller.pi[1].pIController_sw[2].yMax",
   "Output of PI controller yInitial must be between limits.");
DYNX(W_,145) = IF DYNX(W_,158) THEN (IF GreaterS(DYNX(W_,159),"Decentral_Controller.pi[1].pIController_sw[2].y_unlim",
   DYNX(DP_,56),"Decentral_Controller.pi[1].pIController_sw[2].yMax", 2) THEN 
  DYNX(DP_,56) ELSE IF LessS(DYNX(W_,159),"Decentral_Controller.pi[1].pIController_sw[2].y_unlim",
   DYNX(W_,153),"Decentral_Controller.pi[1].pIController_sw[2].yMin", 3) THEN 
  DYNX(W_,153) ELSE DYNX(W_,159)) ELSE DYNX(W_,160);
InitialSection
DYNX(Aux_,2) = DYNX(W_,145);
DYNX(Aux_,3) = DYNX(W_,160);
InitialSection2
DYNX(W_,104) = DYNX(DP_,18);
DYNX(W_,167) = DYNX(W_,104);
DYNX(W_,177) = DYNX(W_,167);
DYNX(W_,192) = DYNX(W_,177);
DYNX(W_,112) = DYNX(DP_,26);
DYNX(W_,171) = DYNX(W_,112);
DYNX(W_,184) = DYNX(W_,171);
DYNX(W_,191) = DYNX(W_,184)*DYNX(U_,0)-DYNX(Y_,0);
DYNX(X_,6) = DYNX(DP_,65)-DYNX(W_,192)*DYNX(W_,191);
DYNX(W_,187) = GreaterEqualTime(DYNX(DP_,66), 2);
DYNX(W_,188) = DYNX(W_,192)*DYNX(W_,191)+DYNX(X_,6);
DYNX(W_,182) =  -DYNX(DP_,64);
AssertModelica(DYNX(DP_,64) >= DYNX(W_,182),"Decentral_Controller.pi[2].pIController_sw[1].yMax >= Decentral_Controller.pi[2].pIController_sw[1].yMin",
   StringAdd(StringAdd(StringAdd(StringAdd("PI controller output limits are not consistent: yMax (=",
  Real2String2(DYNX(DP_,64), true, 0)),") < yMin (="),Real2String2(DYNX(W_,182),
   true, 0)),")"));
PopAllMarks();
AssertModelica(DYNX(DP_,65) >= DYNX(W_,182) AND DYNX(DP_,65) <= DYNX(DP_,64),
  "Decentral_Controller.pi[2].pIController_sw[1].yInitial >= Decentral_Controller.pi[2].pIController_sw[1].yMin and Decentral_Controller.pi[2].pIController_sw[1].yInitial <= Decentral_Controller.pi[2].pIController_sw[1].yMax",
   "Output of PI controller yInitial must be between limits.");
DYNX(W_,174) = IF DYNX(W_,187) THEN (IF GreaterS(DYNX(W_,188),"Decentral_Controller.pi[2].pIController_sw[1].y_unlim",
   DYNX(DP_,64),"Decentral_Controller.pi[2].pIController_sw[1].yMax", 4) THEN 
  DYNX(DP_,64) ELSE IF LessS(DYNX(W_,188),"Decentral_Controller.pi[2].pIController_sw[1].y_unlim",
   DYNX(W_,182),"Decentral_Controller.pi[2].pIController_sw[1].yMin", 5) THEN 
  DYNX(W_,182) ELSE DYNX(W_,188)) ELSE DYNX(W_,189);
InitialSection
DYNX(Aux_,4) = DYNX(W_,174);
DYNX(Aux_,5) = DYNX(W_,189);
InitialSection2
DYNX(W_,105) = DYNX(DP_,19);
DYNX(W_,168) = DYNX(W_,105);
DYNX(W_,198) = DYNX(W_,168);
DYNX(W_,213) = DYNX(W_,198);
DYNX(W_,113) = DYNX(DP_,27);
DYNX(W_,172) = DYNX(W_,113);
DYNX(W_,205) = DYNX(W_,172);
DYNX(W_,212) = DYNX(W_,205)*DYNX(U_,1)-DYNX(Y_,1);
DYNX(X_,7) = DYNX(DP_,70)-DYNX(W_,213)*DYNX(W_,212);
DYNX(W_,208) = GreaterEqualTime(DYNX(DP_,71), 3);
DYNX(W_,209) = DYNX(W_,213)*DYNX(W_,212)+DYNX(X_,7);
DYNX(W_,203) =  -DYNX(DP_,69);
AssertModelica(DYNX(DP_,69) >= DYNX(W_,203),"Decentral_Controller.pi[2].pIController_sw[2].yMax >= Decentral_Controller.pi[2].pIController_sw[2].yMin",
   StringAdd(StringAdd(StringAdd(StringAdd("PI controller output limits are not consistent: yMax (=",
  Real2String2(DYNX(DP_,69), true, 0)),") < yMin (="),Real2String2(DYNX(W_,203),
   true, 0)),")"));
PopAllMarks();
AssertModelica(DYNX(DP_,70) >= DYNX(W_,203) AND DYNX(DP_,70) <= DYNX(DP_,69),
  "Decentral_Controller.pi[2].pIController_sw[2].yInitial >= Decentral_Controller.pi[2].pIController_sw[2].yMin and Decentral_Controller.pi[2].pIController_sw[2].yInitial <= Decentral_Controller.pi[2].pIController_sw[2].yMax",
   "Output of PI controller yInitial must be between limits.");
DYNX(W_,195) = IF DYNX(W_,208) THEN (IF GreaterS(DYNX(W_,209),"Decentral_Controller.pi[2].pIController_sw[2].y_unlim",
   DYNX(DP_,69),"Decentral_Controller.pi[2].pIController_sw[2].yMax", 6) THEN 
  DYNX(DP_,69) ELSE IF LessS(DYNX(W_,209),"Decentral_Controller.pi[2].pIController_sw[2].y_unlim",
   DYNX(W_,203),"Decentral_Controller.pi[2].pIController_sw[2].yMin", 7) THEN 
  DYNX(W_,203) ELSE DYNX(W_,209)) ELSE DYNX(W_,210);
InitialSection
DYNX(Aux_,6) = DYNX(W_,195);
DYNX(Aux_,7) = DYNX(W_,210);
InitialSection2
DYNX(W_,6) = DYNX(DP_,3);
DYNX(W_,63) = DYNX(W_,6);
DYNX(W_,84) = DYNX(W_,63);
DYNX(W_,93) = DYNX(W_,84);
DYNX(W_,14) = DYNX(DP_,11);
DYNX(W_,67) = DYNX(W_,14);
DYNX(W_,86) = DYNX(W_,67);
DYNX(W_,13) = DYNX(DP_,10);
DYNX(W_,66) = DYNX(W_,13);
DYNX(W_,85) = DYNX(W_,66);
DYNX(W_,95) = IF DYNX(W_,86) > 1E-013*sqrtGuarded(DYNX(W_,85)*DYNX(W_,85)+
  DYNX(W_,86)*DYNX(W_,86),"System.miso[2].transferFunction[2].a[1]*System.miso[2].transferFunction[2].a[1]+System.miso[2].transferFunction[2].a[2]*System.miso[2].transferFunction[2].a[2]")
   THEN DYNX(W_,86) ELSE 1.0;
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,4) = divmacro(1.0,"1.0",DYNX(W_,95),"System.miso[2].transferFunction[2].a_end");
DYNX(X_,3) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,4)*DYNX(W_,93)," -System.miso[2].transferFunction[2].bb[2]/System.miso[2].transferFunction[2].a_end",
    -DYNX(W_,83)," -System.miso[2].transferFunction[2].y", DYNX(X_,3),
  "System.miso[2].transferFunction[2].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,4) = DYNX(DP_,1);
DYNX(W_,23) = DYNX(W_,4);
DYNX(W_,44) = DYNX(W_,23);
DYNX(W_,53) = DYNX(W_,44);
DYNX(W_,10) = DYNX(DP_,7);
DYNX(W_,27) = DYNX(W_,10);
DYNX(W_,46) = DYNX(W_,27);
DYNX(W_,9) = DYNX(DP_,6);
DYNX(W_,26) = DYNX(W_,9);
DYNX(W_,45) = DYNX(W_,26);
DYNX(W_,55) = IF DYNX(W_,46) > 1E-013*sqrtGuarded(DYNX(W_,45)*DYNX(W_,45)+
  DYNX(W_,46)*DYNX(W_,46),"System.miso[1].transferFunction[2].a[1]*System.miso[1].transferFunction[2].a[1]+System.miso[1].transferFunction[2].a[2]*System.miso[1].transferFunction[2].a[2]")
   THEN DYNX(W_,46) ELSE 1.0;
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,5) = divmacro(1.0,"1.0",DYNX(W_,55),"System.miso[1].transferFunction[2].a_end");
DYNX(X_,1) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,5)*DYNX(W_,53)," -System.miso[1].transferFunction[2].bb[2]/System.miso[1].transferFunction[2].a_end",
    -DYNX(W_,43)," -System.miso[1].transferFunction[2].y", DYNX(X_,1),
  "System.miso[1].transferFunction[2].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,3) = DYNX(DP_,0);
DYNX(W_,22) = DYNX(W_,3);
DYNX(W_,31) = DYNX(W_,22);
DYNX(W_,40) = DYNX(W_,31);
DYNX(W_,8) = DYNX(DP_,5);
DYNX(W_,25) = DYNX(W_,8);
DYNX(W_,33) = DYNX(W_,25);
DYNX(W_,7) = DYNX(DP_,4);
DYNX(W_,24) = DYNX(W_,7);
DYNX(W_,32) = DYNX(W_,24);
DYNX(W_,42) = IF DYNX(W_,33) > 1E-013*sqrtGuarded(DYNX(W_,32)*DYNX(W_,32)+
  DYNX(W_,33)*DYNX(W_,33),"System.miso[1].transferFunction[1].a[1]*System.miso[1].transferFunction[1].a[1]+System.miso[1].transferFunction[1].a[2]*System.miso[1].transferFunction[1].a[2]")
   THEN DYNX(W_,33) ELSE 1.0;
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,6) = divmacro(1.0,"1.0",DYNX(W_,42),"System.miso[1].transferFunction[1].a_end");
DYNX(X_,0) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,6)*DYNX(W_,40)," -System.miso[1].transferFunction[1].bb[2]/System.miso[1].transferFunction[1].a_end",
    -DYNX(W_,30)," -System.miso[1].transferFunction[1].y", DYNX(X_,0),
  "System.miso[1].transferFunction[1].x_scaled[1]");
 /* End of Equation Block */ 

DYNX(W_,5) = DYNX(DP_,2);
DYNX(W_,62) = DYNX(W_,5);
DYNX(W_,71) = DYNX(W_,62);
DYNX(W_,80) = DYNX(W_,71);
DYNX(W_,12) = DYNX(DP_,9);
DYNX(W_,65) = DYNX(W_,12);
DYNX(W_,73) = DYNX(W_,65);
DYNX(W_,11) = DYNX(DP_,8);
DYNX(W_,64) = DYNX(W_,11);
DYNX(W_,72) = DYNX(W_,64);
DYNX(W_,82) = IF DYNX(W_,73) > 1E-013*sqrtGuarded(DYNX(W_,72)*DYNX(W_,72)+
  DYNX(W_,73)*DYNX(W_,73),"System.miso[2].transferFunction[1].a[1]*System.miso[2].transferFunction[1].a[1]+System.miso[2].transferFunction[1].a[2]*System.miso[2].transferFunction[1].a[2]")
   THEN DYNX(W_,73) ELSE 1.0;
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 1 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,7) = divmacro(1.0,"1.0",DYNX(W_,82),"System.miso[2].transferFunction[1].a_end");
DYNX(X_,2) = 0.0;
SolveScalarLinearParametric( -DYNX(DYNhelp,7)*DYNX(W_,80)," -System.miso[2].transferFunction[1].bb[2]/System.miso[2].transferFunction[1].a_end",
    -DYNX(W_,70)," -System.miso[2].transferFunction[1].y", DYNX(X_,2),
  "System.miso[2].transferFunction[1].x_scaled[1]");
 /* End of Equation Block */ 

InitialSection2
DYNX(W_,114) = DYNX(DP_,47)*DYNX(W_,124)+DYNX(DP_,48)*DYNX(W_,145);
DYNX(W_,115) = DYNX(DP_,60)*DYNX(W_,174)+DYNX(DP_,61)*DYNX(W_,195);
DYNX(W_,219) = DYNX(DP_,30);
DYNX(W_,220) = DYNX(DP_,31);
DYNX(W_,20) = DYNX(W_,219)*DYNX(W_,114)+DYNX(W_,220)*DYNX(W_,115);
DYNX(F_,3) = divmacro(DYNX(W_,95)*DYNX(W_,20)-DYNX(W_,86)*DYNX(X_,3),
  "System.miso[2].transferFunction[2].a_end*System.u[2]-System.miso[2].transferFunction[2].a[2]*System.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,85),"System.miso[2].transferFunction[2].a[1]");
DYNX(W_,125) = DYNX(U_,0)-DYNX(Y_,0);
DYNX(W_,140) = divmacro(DYNX(W_,124)-DYNX(W_,138),"Decentral_Controller.pi[1].pIController_sw[1].y-Decentral_Controller.pi[1].pIController_sw[1].y_unlim",
  DYNX(W_,142),"Decentral_Controller.pi[1].pIController_sw[1].k_in_.k");
DYNX(W_,106) = DYNX(DP_,20);
DYNX(W_,119) = DYNX(W_,106);
DYNX(W_,128) = DYNX(W_,119);
DYNX(W_,143) = DYNX(W_,128);
DYNX(F_,4) = IF DYNX(W_,137) THEN DYNX(W_,143)*(DYNX(W_,125)+DYNX(W_,140)) ELSE 
  0.0;
DYNX(W_,196) = DYNX(U_,1)-DYNX(Y_,1);
DYNX(W_,211) = divmacro(DYNX(W_,195)-DYNX(W_,209),"Decentral_Controller.pi[2].pIController_sw[2].y-Decentral_Controller.pi[2].pIController_sw[2].y_unlim",
  DYNX(W_,213),"Decentral_Controller.pi[2].pIController_sw[2].k_in_.k");
DYNX(W_,109) = DYNX(DP_,23);
DYNX(W_,170) = DYNX(W_,109);
DYNX(W_,199) = DYNX(W_,170);
DYNX(W_,214) = DYNX(W_,199);
DYNX(F_,7) = IF DYNX(W_,208) THEN DYNX(W_,214)*(DYNX(W_,196)+DYNX(W_,211)) ELSE 
  0.0;
DYNX(W_,175) = DYNX(U_,0)-DYNX(Y_,0);
DYNX(W_,190) = divmacro(DYNX(W_,174)-DYNX(W_,188),"Decentral_Controller.pi[2].pIController_sw[1].y-Decentral_Controller.pi[2].pIController_sw[1].y_unlim",
  DYNX(W_,192),"Decentral_Controller.pi[2].pIController_sw[1].k_in_.k");
DYNX(W_,108) = DYNX(DP_,22);
DYNX(W_,169) = DYNX(W_,108);
DYNX(W_,178) = DYNX(W_,169);
DYNX(W_,193) = DYNX(W_,178);
DYNX(F_,6) = IF DYNX(W_,187) THEN DYNX(W_,193)*(DYNX(W_,175)+DYNX(W_,190)) ELSE 
  0.0;
DYNX(F_,1) = divmacro(DYNX(W_,55)*DYNX(W_,20)-DYNX(W_,46)*DYNX(X_,1),
  "System.miso[1].transferFunction[2].a_end*System.u[2]-System.miso[1].transferFunction[2].a[2]*System.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,45),"System.miso[1].transferFunction[2].a[1]");
DYNX(W_,217) = DYNX(DP_,28);
DYNX(W_,218) = DYNX(DP_,29);
DYNX(W_,19) = DYNX(W_,217)*DYNX(W_,114)+DYNX(W_,218)*DYNX(W_,115);
DYNX(F_,0) = divmacro(DYNX(W_,42)*DYNX(W_,19)-DYNX(W_,33)*DYNX(X_,0),
  "System.miso[1].transferFunction[1].a_end*System.u[1]-System.miso[1].transferFunction[1].a[2]*System.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,32),"System.miso[1].transferFunction[1].a[1]");
DYNX(F_,2) = divmacro(DYNX(W_,82)*DYNX(W_,19)-DYNX(W_,73)*DYNX(X_,2),
  "System.miso[2].transferFunction[1].a_end*System.u[1]-System.miso[2].transferFunction[1].a[2]*System.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,72),"System.miso[2].transferFunction[1].a[1]");
DYNX(W_,146) = DYNX(U_,1)-DYNX(Y_,1);
DYNX(W_,161) = divmacro(DYNX(W_,145)-DYNX(W_,159),"Decentral_Controller.pi[1].pIController_sw[2].y-Decentral_Controller.pi[1].pIController_sw[2].y_unlim",
  DYNX(W_,163),"Decentral_Controller.pi[1].pIController_sw[2].k_in_.k");
DYNX(W_,107) = DYNX(DP_,21);
DYNX(W_,120) = DYNX(W_,107);
DYNX(W_,149) = DYNX(W_,120);
DYNX(W_,164) = DYNX(W_,149);
DYNX(F_,5) = IF DYNX(W_,158) THEN DYNX(W_,164)*(DYNX(W_,146)+DYNX(W_,161)) ELSE 
  0.0;
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(W_,30) = divmacro(DYNX(W_,40)*DYNX(X_,0),"System.miso[1].transferFunction[1].bb[2]*System.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,42),"System.miso[1].transferFunction[1].a_end");
DYNX(W_,57) = delay(DYNX(W_,30), DYNX(W_,59), DYNX(W_,59), 4, "delay(System.miso[1].transferFunction[1].y, System.miso[1].fixedDelay[1].delayTime)");
DYNX(W_,43) = divmacro(DYNX(W_,53)*DYNX(X_,1),"System.miso[1].transferFunction[2].bb[2]*System.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,55),"System.miso[1].transferFunction[2].a_end");
DYNX(W_,58) = delay(DYNX(W_,43), DYNX(W_,60), DYNX(W_,60), 5, "delay(System.miso[1].transferFunction[2].y, System.miso[1].fixedDelay[2].delayTime)");
DYNX(Y_,0) = DYNX(DP_,37)*DYNX(W_,57)+DYNX(DP_,38)*DYNX(W_,58);
DYNX(W_,70) = divmacro(DYNX(W_,80)*DYNX(X_,2),"System.miso[2].transferFunction[1].bb[2]*System.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,82),"System.miso[2].transferFunction[1].a_end");
DYNX(W_,97) = delay(DYNX(W_,70), DYNX(W_,99), DYNX(W_,99), 6, "delay(System.miso[2].transferFunction[1].y, System.miso[2].fixedDelay[1].delayTime)");
DYNX(W_,83) = divmacro(DYNX(W_,93)*DYNX(X_,3),"System.miso[2].transferFunction[2].bb[2]*System.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,95),"System.miso[2].transferFunction[2].a_end");
DYNX(W_,98) = delay(DYNX(W_,83), DYNX(W_,100), DYNX(W_,100), 7, "delay(System.miso[2].transferFunction[2].y, System.miso[2].fixedDelay[2].delayTime)");
DYNX(Y_,1) = DYNX(DP_,44)*DYNX(W_,97)+DYNX(DP_,45)*DYNX(W_,98);

DynamicsSection
DYNX(W_,137) = GreaterEqualTime(DYNX(DP_,53), 0);
DYNX(W_,141) = DYNX(W_,134)*DYNX(U_,0)-DYNX(Y_,0);
DYNX(W_,138) = DYNX(W_,142)*DYNX(W_,141)+DYNX(X_,4);
beginwhenBlock
whenModelica( NOT DYNX(W_,137) AND  NOT initial(), 0) 
  DYNX(W_,139) = PRE(DYNX(W_,124), 0);
endwhenModelica()
endwhenBlock

DYNX(W_,124) = IF DYNX(W_,137) THEN (IF GreaterS(DYNX(W_,138),"Decentral_Controller.pi[1].pIController_sw[1].y_unlim",
   DYNX(DP_,51),"Decentral_Controller.pi[1].pIController_sw[1].yMax", 0) THEN 
  DYNX(DP_,51) ELSE IF LessS(DYNX(W_,138),"Decentral_Controller.pi[1].pIController_sw[1].y_unlim",
   DYNX(W_,132),"Decentral_Controller.pi[1].pIController_sw[1].yMin", 1) THEN 
  DYNX(W_,132) ELSE DYNX(W_,138)) ELSE DYNX(W_,139);
DYNX(W_,158) = GreaterEqualTime(DYNX(DP_,58), 1);
DYNX(W_,162) = DYNX(W_,155)*DYNX(U_,1)-DYNX(Y_,1);
DYNX(W_,159) = DYNX(W_,163)*DYNX(W_,162)+DYNX(X_,5);
beginwhenBlock
whenModelica( NOT DYNX(W_,158) AND  NOT initial(), 1) 
  DYNX(W_,160) = PRE(DYNX(W_,145), 1);
endwhenModelica()
endwhenBlock

DYNX(W_,145) = IF DYNX(W_,158) THEN (IF GreaterS(DYNX(W_,159),"Decentral_Controller.pi[1].pIController_sw[2].y_unlim",
   DYNX(DP_,56),"Decentral_Controller.pi[1].pIController_sw[2].yMax", 2) THEN 
  DYNX(DP_,56) ELSE IF LessS(DYNX(W_,159),"Decentral_Controller.pi[1].pIController_sw[2].y_unlim",
   DYNX(W_,153),"Decentral_Controller.pi[1].pIController_sw[2].yMin", 3) THEN 
  DYNX(W_,153) ELSE DYNX(W_,159)) ELSE DYNX(W_,160);
DYNX(W_,114) = DYNX(DP_,47)*DYNX(W_,124)+DYNX(DP_,48)*DYNX(W_,145);
DYNX(W_,187) = GreaterEqualTime(DYNX(DP_,66), 2);
DYNX(W_,191) = DYNX(W_,184)*DYNX(U_,0)-DYNX(Y_,0);
DYNX(W_,188) = DYNX(W_,192)*DYNX(W_,191)+DYNX(X_,6);
beginwhenBlock
whenModelica( NOT DYNX(W_,187) AND  NOT initial(), 2) 
  DYNX(W_,189) = PRE(DYNX(W_,174), 2);
endwhenModelica()
endwhenBlock

DYNX(W_,174) = IF DYNX(W_,187) THEN (IF GreaterS(DYNX(W_,188),"Decentral_Controller.pi[2].pIController_sw[1].y_unlim",
   DYNX(DP_,64),"Decentral_Controller.pi[2].pIController_sw[1].yMax", 4) THEN 
  DYNX(DP_,64) ELSE IF LessS(DYNX(W_,188),"Decentral_Controller.pi[2].pIController_sw[1].y_unlim",
   DYNX(W_,182),"Decentral_Controller.pi[2].pIController_sw[1].yMin", 5) THEN 
  DYNX(W_,182) ELSE DYNX(W_,188)) ELSE DYNX(W_,189);
DYNX(W_,208) = GreaterEqualTime(DYNX(DP_,71), 3);
DYNX(W_,212) = DYNX(W_,205)*DYNX(U_,1)-DYNX(Y_,1);
DYNX(W_,209) = DYNX(W_,213)*DYNX(W_,212)+DYNX(X_,7);
beginwhenBlock
whenModelica( NOT DYNX(W_,208) AND  NOT initial(), 3) 
  DYNX(W_,210) = PRE(DYNX(W_,195), 3);
endwhenModelica()
endwhenBlock

DYNX(W_,195) = IF DYNX(W_,208) THEN (IF GreaterS(DYNX(W_,209),"Decentral_Controller.pi[2].pIController_sw[2].y_unlim",
   DYNX(DP_,69),"Decentral_Controller.pi[2].pIController_sw[2].yMax", 6) THEN 
  DYNX(DP_,69) ELSE IF LessS(DYNX(W_,209),"Decentral_Controller.pi[2].pIController_sw[2].y_unlim",
   DYNX(W_,203),"Decentral_Controller.pi[2].pIController_sw[2].yMin", 7) THEN 
  DYNX(W_,203) ELSE DYNX(W_,209)) ELSE DYNX(W_,210);
DYNX(W_,115) = DYNX(DP_,60)*DYNX(W_,174)+DYNX(DP_,61)*DYNX(W_,195);
DYNX(W_,20) = DYNX(W_,219)*DYNX(W_,114)+DYNX(W_,220)*DYNX(W_,115);
DYNX(F_,3) = divmacro(DYNX(W_,95)*DYNX(W_,20)-DYNX(W_,86)*DYNX(X_,3),
  "System.miso[2].transferFunction[2].a_end*System.u[2]-System.miso[2].transferFunction[2].a[2]*System.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,85),"System.miso[2].transferFunction[2].a[1]");
DYNX(W_,125) = DYNX(U_,0)-DYNX(Y_,0);
DYNX(W_,140) = divmacro(DYNX(W_,124)-DYNX(W_,138),"Decentral_Controller.pi[1].pIController_sw[1].y-Decentral_Controller.pi[1].pIController_sw[1].y_unlim",
  DYNX(W_,142),"Decentral_Controller.pi[1].pIController_sw[1].k_in_.k");
DYNX(F_,4) = IF DYNX(W_,137) THEN DYNX(W_,143)*(DYNX(W_,125)+DYNX(W_,140)) ELSE 
  0.0;
DYNX(W_,196) = DYNX(U_,1)-DYNX(Y_,1);
DYNX(W_,211) = divmacro(DYNX(W_,195)-DYNX(W_,209),"Decentral_Controller.pi[2].pIController_sw[2].y-Decentral_Controller.pi[2].pIController_sw[2].y_unlim",
  DYNX(W_,213),"Decentral_Controller.pi[2].pIController_sw[2].k_in_.k");
DYNX(F_,7) = IF DYNX(W_,208) THEN DYNX(W_,214)*(DYNX(W_,196)+DYNX(W_,211)) ELSE 
  0.0;
DYNX(W_,175) = DYNX(U_,0)-DYNX(Y_,0);
DYNX(W_,190) = divmacro(DYNX(W_,174)-DYNX(W_,188),"Decentral_Controller.pi[2].pIController_sw[1].y-Decentral_Controller.pi[2].pIController_sw[1].y_unlim",
  DYNX(W_,192),"Decentral_Controller.pi[2].pIController_sw[1].k_in_.k");
DYNX(F_,6) = IF DYNX(W_,187) THEN DYNX(W_,193)*(DYNX(W_,175)+DYNX(W_,190)) ELSE 
  0.0;
DYNX(F_,1) = divmacro(DYNX(W_,55)*DYNX(W_,20)-DYNX(W_,46)*DYNX(X_,1),
  "System.miso[1].transferFunction[2].a_end*System.u[2]-System.miso[1].transferFunction[2].a[2]*System.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,45),"System.miso[1].transferFunction[2].a[1]");
DYNX(W_,19) = DYNX(W_,217)*DYNX(W_,114)+DYNX(W_,218)*DYNX(W_,115);
DYNX(F_,0) = divmacro(DYNX(W_,42)*DYNX(W_,19)-DYNX(W_,33)*DYNX(X_,0),
  "System.miso[1].transferFunction[1].a_end*System.u[1]-System.miso[1].transferFunction[1].a[2]*System.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,32),"System.miso[1].transferFunction[1].a[1]");
DYNX(F_,2) = divmacro(DYNX(W_,82)*DYNX(W_,19)-DYNX(W_,73)*DYNX(X_,2),
  "System.miso[2].transferFunction[1].a_end*System.u[1]-System.miso[2].transferFunction[1].a[2]*System.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,72),"System.miso[2].transferFunction[1].a[1]");
DYNX(W_,146) = DYNX(U_,1)-DYNX(Y_,1);
DYNX(W_,161) = divmacro(DYNX(W_,145)-DYNX(W_,159),"Decentral_Controller.pi[1].pIController_sw[2].y-Decentral_Controller.pi[1].pIController_sw[2].y_unlim",
  DYNX(W_,163),"Decentral_Controller.pi[1].pIController_sw[2].k_in_.k");
DYNX(F_,5) = IF DYNX(W_,158) THEN DYNX(W_,164)*(DYNX(W_,146)+DYNX(W_,161)) ELSE 
  0.0;

AcceptedSection1

AcceptedSection2
DYNX(W_,35) = divmacro(DYNX(X_,0),"System.miso[1].transferFunction[1].x_scaled[1]",
  DYNX(W_,42),"System.miso[1].transferFunction[1].a_end");
DYNX(W_,48) = divmacro(DYNX(X_,1),"System.miso[1].transferFunction[2].x_scaled[1]",
  DYNX(W_,55),"System.miso[1].transferFunction[2].a_end");
DYNX(W_,75) = divmacro(DYNX(X_,2),"System.miso[2].transferFunction[1].x_scaled[1]",
  DYNX(W_,82),"System.miso[2].transferFunction[1].a_end");
DYNX(W_,88) = divmacro(DYNX(X_,3),"System.miso[2].transferFunction[2].x_scaled[1]",
  DYNX(W_,95),"System.miso[2].transferFunction[2].a_end");

DefaultSection
CrossingSection
/* Start of reinit equations */
beginwhenBlock
whenModelica(DYNX(W_,208), 4) 
  reinitNew(DYNX(X_,7), PRE(DYNX(W_,195), 3)-DYNX(W_,213)*DYNX(W_,196), 
  DYNX(DYNhelp,8), DYNX(did_->helpvari_vec,0));
endwhenModelica()
endwhenBlock

beginwhenBlock
whenModelica(DYNX(W_,187), 5) 
  reinitNew(DYNX(X_,6), PRE(DYNX(W_,174), 2)-DYNX(W_,192)*DYNX(W_,175), 
  DYNX(DYNhelp,9), DYNX(did_->helpvari_vec,1));
endwhenModelica()
endwhenBlock

beginwhenBlock
whenModelica(DYNX(W_,158), 6) 
  reinitNew(DYNX(X_,5), PRE(DYNX(W_,145), 1)-DYNX(W_,163)*DYNX(W_,146), 
  DYNX(DYNhelp,10), DYNX(did_->helpvari_vec,2));
endwhenModelica()
endwhenBlock

beginwhenBlock
whenModelica(DYNX(W_,137), 7) 
  reinitNew(DYNX(X_,4), PRE(DYNX(W_,124), 0)-DYNX(W_,142)*DYNX(W_,125), 
  DYNX(DYNhelp,11), DYNX(did_->helpvari_vec,3));
endwhenModelica()
endwhenBlock

/* End of reinit equations */
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("n", "Number of in- and outputs [:#(type=Integer)]", 2, 0.0,0.0,\
0.0,0,517)
DeclareVariable("o", "Order of the Process [:#(type=Integer)]", 2, 0.0,0.0,0.0,0,517)
DeclareParameter("num[1, 1, 1]", "Numerator of the system", 0, 1E-010, 0.0,0.0,\
0.0,0,560)
DeclareParameter("num[1, 2, 1]", "Numerator of the system", 1, 1E-010, 0.0,0.0,\
0.0,0,560)
DeclareParameter("num[2, 1, 1]", "Numerator of the system", 2, 1E-010, 0.0,0.0,\
0.0,0,560)
DeclareParameter("num[2, 2, 1]", "Numerator of the system", 3, 1E-010, 0.0,0.0,\
0.0,0,560)
DeclareParameter("den[1, 1, 1]", "Denominator of the system", 4, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 1, 2]", "Denominator of the system", 5, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 2, 1]", "Denominator of the system", 6, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[1, 2, 2]", "Denominator of the system", 7, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 1]", "Denominator of the system", 8, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 1, 2]", "Denominator of the system", 9, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 1]", "Denominator of the system", 10, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("den[2, 2, 2]", "Denominator of the system", 11, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("delay[1, 1]", "Delay of the system for every transfer function",\
 12, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("delay[1, 2]", "Delay of the system for every transfer function",\
 13, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("delay[2, 1]", "Delay of the system for every transfer function",\
 14, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("delay[2, 2]", "Delay of the system for every transfer function",\
 15, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("kp[1, 1]", "Proportional gain of the controller", 16, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("kp[1, 2]", "Proportional gain of the controller", 17, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("kp[2, 1]", "Proportional gain of the controller", 18, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("kp[2, 2]", "Proportional gain of the controller", 19, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("ki[1, 1]", "Integral gain of the controller", 20, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("ki[1, 2]", "Integral gain of the controller", 21, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("ki[2, 1]", "Integral gain of the controller", 22, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("ki[2, 2]", "Integral gain of the controller", 23, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("b[1, 1]", "Set Point Weight of the controller", 24, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("b[1, 2]", "Set Point Weight of the controller", 25, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("b[2, 1]", "Set Point Weight of the controller", 26, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("b[2, 2]", "Set Point Weight of the controller", 27, 1E-010, \
0.0,0.0,0.0,0,560)
DeclareParameter("d[1, 1]", "Decoupler of the System", 28, 1E-010, 0.0,0.0,0.0,0,560)
DeclareParameter("d[1, 2]", "Decoupler of the System", 29, 1E-010, 0.0,0.0,0.0,0,560)
DeclareParameter("d[2, 1]", "Decoupler of the System", 30, 1E-010, 0.0,0.0,0.0,0,560)
DeclareParameter("d[2, 2]", "Decoupler of the System", 31, 1E-010, 0.0,0.0,0.0,0,560)
DeclareVariable("System.n", "Number of inputs (= number of outputs) [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("System.num[1, 1, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("System.num[1, 2, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("System.num[2, 1, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("System.num[2, 2, 1]", "Numerator of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("System.den[1, 1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.den[1, 1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.den[1, 2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.den[1, 2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.den[2, 1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.den[2, 1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.den[2, 2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.den[2, 2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.delay[1, 1]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.delay[1, 2]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.delay[2, 1]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.delay[2, 2]", "Delay for the system", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.u[1]", "Connector of Real input signals", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("System.u[2]", "Connector of Real input signals", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareAlias2("System.y[1]", "Connector of Real output signals", "y[1]", 1, 3, 0,\
 0)
DeclareAlias2("System.y[2]", "Connector of Real output signals", "y[2]", 1, 3, 1,\
 0)
DeclareVariable("System.miso[1].n", "Number of inputs [:#(type=Integer)]", 2, \
0.0,0.0,0.0,0,517)
DeclareVariable("System.miso[1].num[1, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].num[2, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].den[1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].den[1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].den[2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].den[2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].delay[1]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("System.miso[1].delay[2]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("System.miso[1].u[1]", "Connector of Real input signals", \
"System.u[1]", 1, 5, 19, 0)
DeclareAlias2("System.miso[1].u[2]", "Connector of Real input signals", \
"System.u[2]", 1, 5, 20, 0)
DeclareAlias2("System.miso[1].y", "Connector of Real output signal", "y[1]", 1, 3,\
 0, 0)
DeclareAlias2("System.miso[1].transferFunction[1].u", "Connector of Real input signal",\
 "System.u[1]", 1, 5, 19, 0)
DeclareVariable("System.miso[1].transferFunction[1].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[1].transferFunction[1].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].transferFunction[1].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].transferFunction[1].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].transferFunction[1].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("System.miso[1].transferFunction[1].x_start[1]", \
"Initial or guess values of states", 32, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("System.miso[1].transferFunction[1].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 33, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("System.miso[1].transferFunction[1].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[1].transferFunction[1].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[1].transferFunction[1].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[1].transferFunction[1].nx", "[:#(type=Integer)]", 1,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[1].transferFunction[1].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[1].transferFunction[1].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[1].transferFunction[1].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("System.miso[1].transferFunction[1].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("System.miso[1].transferFunction[1].x_scaled[1]", "Scaled vector x",\
 0, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("System.miso[1].transferFunction[1].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("System.miso[1].transferFunction[2].u", "Connector of Real input signal",\
 "System.u[2]", 1, 5, 20, 0)
DeclareVariable("System.miso[1].transferFunction[2].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[1].transferFunction[2].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].transferFunction[2].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].transferFunction[2].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[1].transferFunction[2].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("System.miso[1].transferFunction[2].x_start[1]", \
"Initial or guess values of states", 34, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("System.miso[1].transferFunction[2].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 35, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("System.miso[1].transferFunction[2].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[1].transferFunction[2].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[1].transferFunction[2].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[1].transferFunction[2].nx", "[:#(type=Integer)]", 1,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[1].transferFunction[2].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[1].transferFunction[2].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[1].transferFunction[2].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("System.miso[1].transferFunction[2].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("System.miso[1].transferFunction[2].x_scaled[1]", "Scaled vector x",\
 1, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("System.miso[1].transferFunction[2].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("System.miso[1].add.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 36, 5, 1.0,1E+100,0.0,0,564)
DeclareVariable("System.miso[1].add.nu", "Number of input connections [:#(type=Integer)]",\
 2, 0.0,1E+100,0.0,0,1541)
DeclareVariable("System.miso[1].add.u[1]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[1].add.u[2]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("System.miso[1].add.y", "", "y[1]", 1, 3, 0, 0)
DeclareParameter("System.miso[1].add.k[1]", "Input gains", 37, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("System.miso[1].add.k[2]", "Input gains", 38, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("System.miso[1].fixedDelay[1].u", "Connector of Real input signal",\
 "System.miso[1].transferFunction[1].y", 1, 5, 30, 0)
DeclareAlias2("System.miso[1].fixedDelay[1].y", "Connector of Real output signal",\
 "System.miso[1].add.u[1]", 1, 5, 57, 0)
DeclareVariable("System.miso[1].fixedDelay[1].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("System.miso[1].fixedDelay[2].u", "Connector of Real input signal",\
 "System.miso[1].transferFunction[2].y", 1, 5, 43, 0)
DeclareAlias2("System.miso[1].fixedDelay[2].y", "Connector of Real output signal",\
 "System.miso[1].add.u[2]", 1, 5, 58, 0)
DeclareVariable("System.miso[1].fixedDelay[2].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].n", "Number of inputs [:#(type=Integer)]", 2, \
0.0,0.0,0.0,0,517)
DeclareVariable("System.miso[2].num[1, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].num[2, 1]", "Numerator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].den[1, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].den[1, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].den[2, 1]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].den[2, 2]", "Denominator of the system", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].delay[1]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("System.miso[2].delay[2]", " Delay of the system", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareAlias2("System.miso[2].u[1]", "Connector of Real input signals", \
"System.u[1]", 1, 5, 19, 0)
DeclareAlias2("System.miso[2].u[2]", "Connector of Real input signals", \
"System.u[2]", 1, 5, 20, 0)
DeclareAlias2("System.miso[2].y", "Connector of Real output signal", "y[2]", 1, 3,\
 1, 0)
DeclareAlias2("System.miso[2].transferFunction[1].u", "Connector of Real input signal",\
 "System.u[1]", 1, 5, 19, 0)
DeclareVariable("System.miso[2].transferFunction[1].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[2].transferFunction[1].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].transferFunction[1].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].transferFunction[1].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].transferFunction[1].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("System.miso[2].transferFunction[1].x_start[1]", \
"Initial or guess values of states", 39, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("System.miso[2].transferFunction[1].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 40, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("System.miso[2].transferFunction[1].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[2].transferFunction[1].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[2].transferFunction[1].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[2].transferFunction[1].nx", "[:#(type=Integer)]", 1,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[2].transferFunction[1].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[2].transferFunction[1].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[2].transferFunction[1].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("System.miso[2].transferFunction[1].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("System.miso[2].transferFunction[1].x_scaled[1]", "Scaled vector x",\
 2, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("System.miso[2].transferFunction[1].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("System.miso[2].transferFunction[2].u", "Connector of Real input signal",\
 "System.u[2]", 1, 5, 20, 0)
DeclareVariable("System.miso[2].transferFunction[2].y", "Connector of Real output signal",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[2].transferFunction[2].b[1]", "Numerator coefficients of transfer function (e.g., 2*s+3 is specified as {2,3})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].transferFunction[2].a[1]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].transferFunction[2].a[2]", "Denominator coefficients of transfer function (e.g., 5*s+6 is specified as {5,6})",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("System.miso[2].transferFunction[2].initType", "Type of initialization (1: no init, 2: steady state, 3: initial state, 4: initial output) [:#(type=Modelica.Blocks.Types.Init)]",\
 4, 1.0,4.0,0.0,0,517)
DeclareParameter("System.miso[2].transferFunction[2].x_start[1]", \
"Initial or guess values of states", 41, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("System.miso[2].transferFunction[2].y_start", "Initial value of output (derivatives of y are zero up to nx-1-th derivative)",\
 42, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("System.miso[2].transferFunction[2].x[1]", "State of transfer function from controller canonical form",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[2].transferFunction[2].na", "Size of Denominator of transfer function. [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[2].transferFunction[2].nb", "Size of Numerator of transfer function. [:#(type=Integer)]",\
 1, 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[2].transferFunction[2].nx", "[:#(type=Integer)]", 1,\
 0.0,0.0,0.0,0,2565)
DeclareVariable("System.miso[2].transferFunction[2].bb[1]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[2].transferFunction[2].bb[2]", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("System.miso[2].transferFunction[2].d", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("System.miso[2].transferFunction[2].a_end", "", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareState("System.miso[2].transferFunction[2].x_scaled[1]", "Scaled vector x",\
 3, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("System.miso[2].transferFunction[2].der(x_scaled[1])", \
"der(Scaled vector x)", 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("System.miso[2].add.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 43, 5, 1.0,1E+100,0.0,0,564)
DeclareVariable("System.miso[2].add.nu", "Number of input connections [:#(type=Integer)]",\
 2, 0.0,1E+100,0.0,0,1541)
DeclareVariable("System.miso[2].add.u[1]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("System.miso[2].add.u[2]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("System.miso[2].add.y", "", "y[2]", 1, 3, 1, 0)
DeclareParameter("System.miso[2].add.k[1]", "Input gains", 44, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("System.miso[2].add.k[2]", "Input gains", 45, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("System.miso[2].fixedDelay[1].u", "Connector of Real input signal",\
 "System.miso[2].transferFunction[1].y", 1, 5, 70, 0)
DeclareAlias2("System.miso[2].fixedDelay[1].y", "Connector of Real output signal",\
 "System.miso[2].add.u[1]", 1, 5, 97, 0)
DeclareVariable("System.miso[2].fixedDelay[1].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareAlias2("System.miso[2].fixedDelay[2].u", "Connector of Real input signal",\
 "System.miso[2].transferFunction[2].y", 1, 5, 83, 0)
DeclareAlias2("System.miso[2].fixedDelay[2].y", "Connector of Real output signal",\
 "System.miso[2].add.u[2]", 1, 5, 98, 0)
DeclareVariable("System.miso[2].fixedDelay[2].delayTime", "Delay time of output with respect to input signal [s]",\
 1, 0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.n", "Number of inputs (= number of outputs) [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("Decentral_Controller.KP[1, 1]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.KP[1, 2]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.KP[2, 1]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.KP[2, 2]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.KI[1, 1]", "Integral Gain", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("Decentral_Controller.KI[1, 2]", "Integral Gain", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("Decentral_Controller.KI[2, 1]", "Integral Gain", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("Decentral_Controller.KI[2, 2]", "Integral Gain", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("Decentral_Controller.B[1, 1]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.B[1, 2]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.B[2, 1]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.B[2, 2]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("Decentral_Controller.u_s[1]", "Connector of Set Point value", \
"u[1]", 1, 2, 0, 0)
DeclareAlias2("Decentral_Controller.u_s[2]", "Connector of Set Point value", \
"u[2]", 1, 2, 1, 0)
DeclareAlias2("Decentral_Controller.u_m[1]", "Connector of measurement value", \
"y[1]", 1, 3, 0, 0)
DeclareAlias2("Decentral_Controller.u_m[2]", "Connector of measurement value", \
"y[2]", 1, 3, 1, 0)
DeclareVariable("Decentral_Controller.y[1]", "Connector of Real output signals",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Decentral_Controller.y[2]", "Connector of Real output signals",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Decentral_Controller.pi[1].n", "Number of inputs [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("Decentral_Controller.pi[1].KP[1]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].KP[2]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].KI[1]", "Integral Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].KI[2]", "Integral Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].B[1]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].B[2]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("Decentral_Controller.pi[1].u_s[1]", "Connector of Set Point value",\
 "u[1]", 1, 2, 0, 0)
DeclareAlias2("Decentral_Controller.pi[1].u_s[2]", "Connector of Set Point value",\
 "u[2]", 1, 2, 1, 0)
DeclareAlias2("Decentral_Controller.pi[1].y", "Connector of Real output signal",\
 "Decentral_Controller.y[1]", 1, 5, 114, 0)
DeclareParameter("Decentral_Controller.pi[1].add.significantDigits", \
"Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 46, 3, 1.0,1E+100,0.0,0,564)
DeclareVariable("Decentral_Controller.pi[1].add.nu", "Number of input connections [:#(type=Integer)]",\
 2, 0.0,1E+100,0.0,0,1541)
DeclareAlias2("Decentral_Controller.pi[1].add.u[1]", "", "Decentral_Controller.pi[1].pIController_sw[1].y", 1,\
 5, 124, 0)
DeclareAlias2("Decentral_Controller.pi[1].add.u[2]", "", "Decentral_Controller.pi[1].pIController_sw[2].y", 1,\
 5, 145, 0)
DeclareAlias2("Decentral_Controller.pi[1].add.y", "", "Decentral_Controller.y[1]", 1,\
 5, 114, 0)
DeclareParameter("Decentral_Controller.pi[1].add.k[1]", "Input gains", 47, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("Decentral_Controller.pi[1].add.k[2]", "Input gains", 48, 1, \
0.0,0.0,0.0,0,560)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].u_s", \
"Connector of setpoint input signal", "u[1]", 1, 2, 0, 0)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].u_m", \
"Connector of measurement input signal", "y[1]", 1, 3, 0, 0)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].y", \
"Connector of actuator output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].u", \
"Differenz between setpoint and measurement aka control error", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].invertFeedback", \
"true, if feedback Modelica.SIUnitsgnal is inverted [:#(type=Boolean)]", false, \
0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[1].offset", \
"Operating point, added to proportional output", 49, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].k", \
"Proportional gain of controller", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[1].Ti", \
"Time constant of Integrator block [s]", 50, 0.5, 1E-060,1E+100,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].ki", \
"Integral gain [s-1]", 1E-060, 1E-060,1E+100,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].use_kInput", \
"= true, if k defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].use_TiInput", \
"= true, if Ti defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].use_kiInput", \
"= true, if ki defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[1].yMax", \
"Upper limit of output", 51, 50, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].yMin", \
"Lower limit of output", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].use_setpointWeighting",\
 "Available for PI [:#(type=Boolean)]", true, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].b", \
"Setpoint weight 0 >= b >= 1", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[1].yInitial", \
"Initial output of controller", 52, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].use_activeInput",\
 "= true, if controller is switched on/off externally [:#(type=Boolean)]", false,\
 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].use_y_notActive",\
 "= true, if output of not activated controller is defined externally. Otherwise output is hold at deactivation. [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[1].activationTime",\
 "Time when controller is switched on [s]", 53, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].getActive.u", \
"Connector of Boolean input signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,2690)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].getActive.y", \
"Connector of Boolean output signal [:#(type=Boolean)]", "Decentral_Controller.pi[1].pIController_sw[1].getActive.u", 1,\
 5, 137, 1089)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].active_.y", \
"Value of Boolean output [:#(type=Boolean)]", "Decentral_Controller.pi[1].pIController_sw[1].getActive.u", 1,\
 5, 137, 1089)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].y_unlim", "", 0.0,\
 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].y_old", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].u_antiWindUp", "",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].u_setpointWeighting",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("Decentral_Controller.pi[1].pIController_sw[1].integral", "", 4, \
0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("Decentral_Controller.pi[1].pIController_sw[1].der(integral)",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].ki_internal", "", \
"Decentral_Controller.pi[1].pIController_sw[1].ki_in_.k", 1, 5, 143, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].getInputs.ki_in", \
"[s-1]", "Decentral_Controller.pi[1].pIController_sw[1].ki_in_.k", 1, 5, 143, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].getInputs.k_in", "",\
 "Decentral_Controller.pi[1].pIController_sw[1].k_in_.k", 1, 5, 142, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].getInputs.Ti_in", \
"[s]", "Decentral_Controller.pi[1].pIController_sw[1].Ti_in_.k", 1, 5, 144, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].getInputs.y_notActive",\
 "", "Decentral_Controller.pi[1].pIController_sw[1].y_old", 1, 5, 139, 1088)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].k_in_.k", \
"Constant output value", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].k_in_.y", \
"Connector of Real output signal", "Decentral_Controller.pi[1].pIController_sw[1].k_in_.k", 1,\
 5, 142, 1024)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].ki_in_.k", \
"Constant output value [s-1]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].ki_in_.y", \
"Connector of Real output signal [s-1]", "Decentral_Controller.pi[1].pIController_sw[1].ki_in_.k", 1,\
 5, 143, 1024)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[1].Ti_in_.k", \
"Constant output value [s]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].Ti_in_.y", \
"Connector of Real output signal [s]", "Decentral_Controller.pi[1].pIController_sw[1].Ti_in_.k", 1,\
 5, 144, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[1].y_notActive_.y", \
"Value of Real output", "Decentral_Controller.pi[1].pIController_sw[1].y_old", 1,\
 5, 139, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].u_s", \
"Connector of setpoint input signal", "u[2]", 1, 2, 1, 0)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].u_m", \
"Connector of measurement input signal", "y[2]", 1, 3, 1, 0)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].y", \
"Connector of actuator output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].u", \
"Differenz between setpoint and measurement aka control error", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].invertFeedback", \
"true, if feedback Modelica.SIUnitsgnal is inverted [:#(type=Boolean)]", false, \
0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[2].offset", \
"Operating point, added to proportional output", 54, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].k", \
"Proportional gain of controller", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[2].Ti", \
"Time constant of Integrator block [s]", 55, 0.5, 1E-060,1E+100,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].ki", \
"Integral gain [s-1]", 1E-060, 1E-060,1E+100,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].use_kInput", \
"= true, if k defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].use_TiInput", \
"= true, if Ti defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].use_kiInput", \
"= true, if ki defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[2].yMax", \
"Upper limit of output", 56, 50, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].yMin", \
"Lower limit of output", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].use_setpointWeighting",\
 "Available for PI [:#(type=Boolean)]", true, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].b", \
"Setpoint weight 0 >= b >= 1", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[2].yInitial", \
"Initial output of controller", 57, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].use_activeInput",\
 "= true, if controller is switched on/off externally [:#(type=Boolean)]", false,\
 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].use_y_notActive",\
 "= true, if output of not activated controller is defined externally. Otherwise output is hold at deactivation. [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[1].pIController_sw[2].activationTime",\
 "Time when controller is switched on [s]", 58, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].getActive.u", \
"Connector of Boolean input signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,2690)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].getActive.y", \
"Connector of Boolean output signal [:#(type=Boolean)]", "Decentral_Controller.pi[1].pIController_sw[2].getActive.u", 1,\
 5, 158, 1089)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].active_.y", \
"Value of Boolean output [:#(type=Boolean)]", "Decentral_Controller.pi[1].pIController_sw[2].getActive.u", 1,\
 5, 158, 1089)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].y_unlim", "", 0.0,\
 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].y_old", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].u_antiWindUp", "",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].u_setpointWeighting",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("Decentral_Controller.pi[1].pIController_sw[2].integral", "", 5, \
0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("Decentral_Controller.pi[1].pIController_sw[2].der(integral)",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].ki_internal", "", \
"Decentral_Controller.pi[1].pIController_sw[2].ki_in_.k", 1, 5, 164, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].getInputs.ki_in", \
"[s-1]", "Decentral_Controller.pi[1].pIController_sw[2].ki_in_.k", 1, 5, 164, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].getInputs.k_in", "",\
 "Decentral_Controller.pi[1].pIController_sw[2].k_in_.k", 1, 5, 163, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].getInputs.Ti_in", \
"[s]", "Decentral_Controller.pi[1].pIController_sw[2].Ti_in_.k", 1, 5, 165, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].getInputs.y_notActive",\
 "", "Decentral_Controller.pi[1].pIController_sw[2].y_old", 1, 5, 160, 1088)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].k_in_.k", \
"Constant output value", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].k_in_.y", \
"Connector of Real output signal", "Decentral_Controller.pi[1].pIController_sw[2].k_in_.k", 1,\
 5, 163, 1024)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].ki_in_.k", \
"Constant output value [s-1]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].ki_in_.y", \
"Connector of Real output signal [s-1]", "Decentral_Controller.pi[1].pIController_sw[2].ki_in_.k", 1,\
 5, 164, 1024)
DeclareVariable("Decentral_Controller.pi[1].pIController_sw[2].Ti_in_.k", \
"Constant output value [s]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].Ti_in_.y", \
"Connector of Real output signal [s]", "Decentral_Controller.pi[1].pIController_sw[2].Ti_in_.k", 1,\
 5, 165, 1024)
DeclareAlias2("Decentral_Controller.pi[1].pIController_sw[2].y_notActive_.y", \
"Value of Real output", "Decentral_Controller.pi[1].pIController_sw[2].y_old", 1,\
 5, 160, 1024)
DeclareAlias2("Decentral_Controller.pi[1].u_m[1]", "Connector of measurement value",\
 "y[1]", 1, 3, 0, 0)
DeclareAlias2("Decentral_Controller.pi[1].u_m[2]", "Connector of measurement value",\
 "y[2]", 1, 3, 1, 0)
DeclareVariable("Decentral_Controller.pi[2].n", "Number of inputs [:#(type=Integer)]",\
 2, 0.0,0.0,0.0,0,517)
DeclareVariable("Decentral_Controller.pi[2].KP[1]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].KP[2]", "Proportional Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].KI[1]", "Integral Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].KI[2]", "Integral Gain", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].B[1]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].B[2]", "Set Point Weights", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("Decentral_Controller.pi[2].u_s[1]", "Connector of Set Point value",\
 "u[1]", 1, 2, 0, 0)
DeclareAlias2("Decentral_Controller.pi[2].u_s[2]", "Connector of Set Point value",\
 "u[2]", 1, 2, 1, 0)
DeclareAlias2("Decentral_Controller.pi[2].y", "Connector of Real output signal",\
 "Decentral_Controller.y[2]", 1, 5, 115, 0)
DeclareParameter("Decentral_Controller.pi[2].add.significantDigits", \
"Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 59, 3, 1.0,1E+100,0.0,0,564)
DeclareVariable("Decentral_Controller.pi[2].add.nu", "Number of input connections [:#(type=Integer)]",\
 2, 0.0,1E+100,0.0,0,1541)
DeclareAlias2("Decentral_Controller.pi[2].add.u[1]", "", "Decentral_Controller.pi[2].pIController_sw[1].y", 1,\
 5, 174, 0)
DeclareAlias2("Decentral_Controller.pi[2].add.u[2]", "", "Decentral_Controller.pi[2].pIController_sw[2].y", 1,\
 5, 195, 0)
DeclareAlias2("Decentral_Controller.pi[2].add.y", "", "Decentral_Controller.y[2]", 1,\
 5, 115, 0)
DeclareParameter("Decentral_Controller.pi[2].add.k[1]", "Input gains", 60, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("Decentral_Controller.pi[2].add.k[2]", "Input gains", 61, 1, \
0.0,0.0,0.0,0,560)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].u_s", \
"Connector of setpoint input signal", "u[1]", 1, 2, 0, 0)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].u_m", \
"Connector of measurement input signal", "y[1]", 1, 3, 0, 0)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].y", \
"Connector of actuator output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].u", \
"Differenz between setpoint and measurement aka control error", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].invertFeedback", \
"true, if feedback Modelica.SIUnitsgnal is inverted [:#(type=Boolean)]", false, \
0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[1].offset", \
"Operating point, added to proportional output", 62, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].k", \
"Proportional gain of controller", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[1].Ti", \
"Time constant of Integrator block [s]", 63, 0.5, 1E-060,1E+100,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].ki", \
"Integral gain [s-1]", 1E-060, 1E-060,1E+100,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].use_kInput", \
"= true, if k defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].use_TiInput", \
"= true, if Ti defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].use_kiInput", \
"= true, if ki defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[1].yMax", \
"Upper limit of output", 64, 50, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].yMin", \
"Lower limit of output", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].use_setpointWeighting",\
 "Available for PI [:#(type=Boolean)]", true, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].b", \
"Setpoint weight 0 >= b >= 1", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[1].yInitial", \
"Initial output of controller", 65, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].use_activeInput",\
 "= true, if controller is switched on/off externally [:#(type=Boolean)]", false,\
 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].use_y_notActive",\
 "= true, if output of not activated controller is defined externally. Otherwise output is hold at deactivation. [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[1].activationTime",\
 "Time when controller is switched on [s]", 66, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].getActive.u", \
"Connector of Boolean input signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,2690)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].getActive.y", \
"Connector of Boolean output signal [:#(type=Boolean)]", "Decentral_Controller.pi[2].pIController_sw[1].getActive.u", 1,\
 5, 187, 1089)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].active_.y", \
"Value of Boolean output [:#(type=Boolean)]", "Decentral_Controller.pi[2].pIController_sw[1].getActive.u", 1,\
 5, 187, 1089)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].y_unlim", "", 0.0,\
 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].y_old", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].u_antiWindUp", "",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].u_setpointWeighting",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("Decentral_Controller.pi[2].pIController_sw[1].integral", "", 6, \
0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("Decentral_Controller.pi[2].pIController_sw[1].der(integral)",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].ki_internal", "", \
"Decentral_Controller.pi[2].pIController_sw[1].ki_in_.k", 1, 5, 193, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].getInputs.ki_in", \
"[s-1]", "Decentral_Controller.pi[2].pIController_sw[1].ki_in_.k", 1, 5, 193, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].getInputs.k_in", "",\
 "Decentral_Controller.pi[2].pIController_sw[1].k_in_.k", 1, 5, 192, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].getInputs.Ti_in", \
"[s]", "Decentral_Controller.pi[2].pIController_sw[1].Ti_in_.k", 1, 5, 194, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].getInputs.y_notActive",\
 "", "Decentral_Controller.pi[2].pIController_sw[1].y_old", 1, 5, 189, 1088)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].k_in_.k", \
"Constant output value", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].k_in_.y", \
"Connector of Real output signal", "Decentral_Controller.pi[2].pIController_sw[1].k_in_.k", 1,\
 5, 192, 1024)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].ki_in_.k", \
"Constant output value [s-1]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].ki_in_.y", \
"Connector of Real output signal [s-1]", "Decentral_Controller.pi[2].pIController_sw[1].ki_in_.k", 1,\
 5, 193, 1024)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[1].Ti_in_.k", \
"Constant output value [s]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].Ti_in_.y", \
"Connector of Real output signal [s]", "Decentral_Controller.pi[2].pIController_sw[1].Ti_in_.k", 1,\
 5, 194, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[1].y_notActive_.y", \
"Value of Real output", "Decentral_Controller.pi[2].pIController_sw[1].y_old", 1,\
 5, 189, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].u_s", \
"Connector of setpoint input signal", "u[2]", 1, 2, 1, 0)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].u_m", \
"Connector of measurement input signal", "y[2]", 1, 3, 1, 0)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].y", \
"Connector of actuator output signal", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].u", \
"Differenz between setpoint and measurement aka control error", 0.0, 0.0,0.0,0.0,\
0,512)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].invertFeedback", \
"true, if feedback Modelica.SIUnitsgnal is inverted [:#(type=Boolean)]", false, \
0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[2].offset", \
"Operating point, added to proportional output", 67, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].k", \
"Proportional gain of controller", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[2].Ti", \
"Time constant of Integrator block [s]", 68, 0.5, 1E-060,1E+100,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].ki", \
"Integral gain [s-1]", 1E-060, 1E-060,1E+100,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].use_kInput", \
"= true, if k defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].use_TiInput", \
"= true, if Ti defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].use_kiInput", \
"= true, if ki defined by input [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[2].yMax", \
"Upper limit of output", 69, 50, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].yMin", \
"Lower limit of output", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].use_setpointWeighting",\
 "Available for PI [:#(type=Boolean)]", true, 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].b", \
"Setpoint weight 0 >= b >= 1", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[2].yInitial", \
"Initial output of controller", 70, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].use_activeInput",\
 "= true, if controller is switched on/off externally [:#(type=Boolean)]", false,\
 0.0,0.0,0.0,0,515)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].use_y_notActive",\
 "= true, if output of not activated controller is defined externally. Otherwise output is hold at deactivation. [:#(type=Boolean)]",\
 false, 0.0,0.0,0.0,0,515)
DeclareParameter("Decentral_Controller.pi[2].pIController_sw[2].activationTime",\
 "Time when controller is switched on [s]", 71, 0.0, 0.0,0.0,0.0,0,560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].getActive.u", \
"Connector of Boolean input signal [:#(type=Boolean)]", false, 0.0,0.0,0.0,0,2690)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].getActive.y", \
"Connector of Boolean output signal [:#(type=Boolean)]", "Decentral_Controller.pi[2].pIController_sw[2].getActive.u", 1,\
 5, 208, 1089)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].active_.y", \
"Value of Boolean output [:#(type=Boolean)]", "Decentral_Controller.pi[2].pIController_sw[2].getActive.u", 1,\
 5, 208, 1089)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].y_unlim", "", 0.0,\
 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].y_old", "", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].u_antiWindUp", "",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].u_setpointWeighting",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareState("Decentral_Controller.pi[2].pIController_sw[2].integral", "", 7, \
0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("Decentral_Controller.pi[2].pIController_sw[2].der(integral)",\
 "", 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].ki_internal", "", \
"Decentral_Controller.pi[2].pIController_sw[2].ki_in_.k", 1, 5, 214, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].getInputs.ki_in", \
"[s-1]", "Decentral_Controller.pi[2].pIController_sw[2].ki_in_.k", 1, 5, 214, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].getInputs.k_in", "",\
 "Decentral_Controller.pi[2].pIController_sw[2].k_in_.k", 1, 5, 213, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].getInputs.Ti_in", \
"[s]", "Decentral_Controller.pi[2].pIController_sw[2].Ti_in_.k", 1, 5, 215, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].getInputs.y_notActive",\
 "", "Decentral_Controller.pi[2].pIController_sw[2].y_old", 1, 5, 210, 1088)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].k_in_.k", \
"Constant output value", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].k_in_.y", \
"Connector of Real output signal", "Decentral_Controller.pi[2].pIController_sw[2].k_in_.k", 1,\
 5, 213, 1024)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].ki_in_.k", \
"Constant output value [s-1]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].ki_in_.y", \
"Connector of Real output signal [s-1]", "Decentral_Controller.pi[2].pIController_sw[2].ki_in_.k", 1,\
 5, 214, 1024)
DeclareVariable("Decentral_Controller.pi[2].pIController_sw[2].Ti_in_.k", \
"Constant output value [s]", 1, 0.0,0.0,0.0,0,2561)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].Ti_in_.y", \
"Connector of Real output signal [s]", "Decentral_Controller.pi[2].pIController_sw[2].Ti_in_.k", 1,\
 5, 215, 1024)
DeclareAlias2("Decentral_Controller.pi[2].pIController_sw[2].y_notActive_.y", \
"Value of Real output", "Decentral_Controller.pi[2].pIController_sw[2].y_old", 1,\
 5, 210, 1024)
DeclareAlias2("Decentral_Controller.pi[2].u_m[1]", "Connector of measurement value",\
 "y[1]", 1, 3, 0, 0)
DeclareAlias2("Decentral_Controller.pi[2].u_m[2]", "Connector of measurement value",\
 "y[2]", 1, 3, 1, 0)
DeclareVariable("Decoupler.n", "Number of inputs [:#(type=Integer)]", 2, \
0.0,0.0,0.0,0,517)
DeclareVariable("Decoupler.D[1, 1]", "Decoupling Matrix", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Decoupler.D[1, 2]", "Decoupling Matrix", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Decoupler.D[2, 1]", "Decoupling Matrix", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Decoupler.D[2, 2]", "Decoupling Matrix", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("Decoupler.u[1]", "Connector of Real input signals", \
"Decentral_Controller.y[1]", 1, 5, 114, 0)
DeclareAlias2("Decoupler.u[2]", "Connector of Real input signals", \
"Decentral_Controller.y[2]", 1, 5, 115, 0)
DeclareAlias2("Decoupler.y[1]", "Connector of Real output signals", \
"System.u[1]", 1, 5, 19, 0)
DeclareAlias2("Decoupler.y[2]", "Connector of Real output signals", \
"System.u[2]", 1, 5, 20, 0)
DeclareInput("u[1]", "Systems set point [:#(prefix=input)]", 0, 0, 0.0,0.0,0.0,0,512)
DeclareInput("u[2]", "Systems set point [:#(prefix=input)]", 1, 0, 0.0,0.0,0.0,0,512)
DeclareOutput("y[1]", "Systems real output", 0, 0, 0.0,0.0,0.0,0,512)
DeclareOutput("y[2]", "Systems real output", 1, 0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void DelayedUpdateReinit(double*time, double* X_, double* W_, double* U_, double* Y_, struct DYNInstanceData*did_) {
if (DYNX(did_->helpvari_vec,0)) {
  DYNX(X_,7)=DYNX(DYNhelp,8);
  DYNX(did_->helpvari_vec,0)=0;
}
if (DYNX(did_->helpvari_vec,1)) {
  DYNX(X_,6)=DYNX(DYNhelp,9);
  DYNX(did_->helpvari_vec,1)=0;
}
if (DYNX(did_->helpvari_vec,2)) {
  DYNX(X_,5)=DYNX(DYNhelp,10);
  DYNX(did_->helpvari_vec,2)=0;
}
if (DYNX(did_->helpvari_vec,3)) {
  DYNX(X_,4)=DYNX(DYNhelp,11);
  DYNX(did_->helpvari_vec,3)=0;
}
}
DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
StartPreBlock
preCont(DYNX(W_,124),"Decentral_Controller.pi[1].pIController_sw[1].y", 
  DYNX(DP_,52), 0);
preCont(DYNX(W_,145),"Decentral_Controller.pi[1].pIController_sw[2].y", 
  DYNX(DP_,57), 1);
preCont(DYNX(W_,174),"Decentral_Controller.pi[2].pIController_sw[1].y", 
  DYNX(DP_,65), 2);
preCont(DYNX(W_,195),"Decentral_Controller.pi[2].pIController_sw[2].y", 
  DYNX(DP_,70), 3);
EndPreBlock
UpdateQEvaluate(8)
EndDataBlock

BreakSectionFunctionStart(0);
BreakSectionFunctionCallNew(1);
BreakSectionFunctionEnd()
